import 'package:pawlinker/model/heading.dart';

List<Heading> HeadingsAdopt = [
  Heading(
    title: "Dogs",
    icon: "https://www.pngkey.com/png/full/113-1134986_dog-face-png.png",
    lists: [
      Details(
        image: [
          "https://tse2.mm.bing.net/th?id=OIP.kUEvpwJ4HrSVwa6xYQ-z2gHaLG&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.4AjcBLC1vQow7c_FVTW_fgHaE8&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.hMt2WyTj2Lw5xlymfpU-pQHaHw&pid=Api&P=0&h=180",
        ],
        title: "Buddy",
        age: 3,
        date: "12-04-2024",
        description:
            "Buddy is a cheerful and loyal Labrador Retriever who thrives on companionship. He enjoys long walks, belly rubs, and fetching tennis balls. His boundless energy and friendly demeanor make him the perfect family dog.\n\nBuddy is incredibly intelligent and picks up commands quickly. Whether you're playing at the park or relaxing at home, he's always by your side with a wagging tail and a happy bark.",
        gender: Gender.Male,
        breed: "Labrador Retriever",
        //isLiked: false,
        isPet: true,
        //price: 900,
      ),
      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.DNWynMAdhjRDfVw8im19GQHaFj&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.Jk3Vvb-wSxuyRlncNmmX8gHaK1&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.otjNv5Jm1JkK4rumNbPXygHaEJ&pid=Api&P=0&h=180",
        ],
        title: "Daisy",
        age: 2,
        date: "05-03-2024",
        description:
            "Daisy is a gentle and affectionate Golden Retriever who adores human attention. Her soft golden coat and soulful eyes make her irresistible to anyone who meets her.\n\nDaisy loves water, running across fields, and cuddling up after a day of play. She's great with children and other pets, making her an ideal addition to any loving home.",
        gender: Gender.Female,
        breed: "Golden Retriever",
        //isLiked: false,
        isPet: true,
        //price: 1100,
      ),
      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.l9Uzz7apVbCZL-vGltjvzAHaEJ&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.jtHXdiw_C4EOTQgZ1q1i_AHaE7&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.wvy5nHqtYTuZVELCGCO9fgHaFz&pid=Api&P=0&h=180",
        ],
        title: "Max",
        age: 4,
        date: "20-02-2024",
        description:
            "Max is a smart and courageous German Shepherd, well-suited for active owners. His loyalty knows no bounds, and he thrives in an environment where he can have a purpose.\n\nWhether he's helping around the house or going on hikes, Max is always alert and ready. His protective instinct and love for family make him a top choice among dog lovers.",
        gender: Gender.Male,
        breed: "German Shepherd",
        //isLiked: false,
        isPet: true,
        //price: 950,
      ),
      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.pSj04D5TcHODT839cFZv5QHaE7&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.aDJxmTTbHkyJZtazGQ4jlgHaE8&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.TXvMjOGrVSzobvDWC77q9AHaE8&pid=Api&P=0&h=180",
        ],
        title: "Bella",
        age: 1,
        date: "25-01-2024",
        description:
            "Bella is a playful Poodle with a big personality packed into a curly coat. She loves learning tricks and showing them off to guests, especially when treats are involved.\n\nKnown for being hypoallergenic, Bella is a great companion for those with allergies. She's sociable, curious, and always ready to explore new places with her humans.",
        gender: Gender.Female,
        breed: "Poodle",
        //isLiked: false,
        isPet: true,
        //price: 1200,
      ),
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.G5VSoNAU-4g9uIUlTz_RUQHaHa&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.EE1iuKrpAA3YLk7M1Ctj_QAAAA&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.ubrhpkML5P5qhM-e0hcO6wHaFL&pid=Api&P=0&h=180",
        ],
        title: "Charlie",
        age: 3,
        date: "15-03-2024",
        description:
            "Charlie is a stocky, charming English Bulldog with a heart full of love. Despite his serious expression, he's a big softie who enjoys naps and short walks in the sun.\n\nHe's low-maintenance, great with kids, and loves being part of the family routine. Charlie thrives on affection and always finds a cozy spot to snuggle beside you.",
        gender: Gender.Male,
        breed: "Bulldog",
        //isLiked: false,
        isPet: true,
        //price: 1000,
      ),
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.cVUrVofdAtZHFow1HINcwwHaE6&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.PRFHmggho2i2jcb_evueVAHaHa&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.CEmnaCMNxifnEof3UKryMwHaEK&pid=Api&P=0&h=180",
        ],
        title: "Luna",
        age: 2,
        date: "30-04-2024",
        description:
            "Luna is an energetic Beagle with a nose for adventure. Her expressive eyes and floppy ears make her the center of attention wherever she goes.\n\nBeagles like Luna love exploring scents, playing with toys, and being around people. She's ideal for someone looking for a curious and happy companion.",
        gender: Gender.Female,
        breed: "Beagle",
        //isLiked: false,
        isPet: true,
        //price: 850,
      ),
      Details(
        image: [
          "https://tse2.mm.bing.net/th?id=OIP.oNKgutHKgRvL-qJ8b0Xr4QHaE8&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.lw3ISrzE7ylNFT_qH41IbgHaLL&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.rwjSywHSH-kQH2ODlVrfQAHaE7&pid=Api&P=0&h=180",
        ],
        title: "Rocky",
        age: 5,
        date: "18-03-2024",
        description:
            "Rocky is a spirited Yorkshire Terrier with a bold attitude packed in a small body. He might be tiny, but his personality is huge!\n\nHe’s alert, vocal, and loves attention. Great for apartment living, Rocky bonds closely with his owner and loves being pampered like royalty.",
        gender: Gender.Male,
        breed: "Yorkshire Terrier",
        //isLiked: false,
        isPet: true,
        //price: 780,
      ),
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.8sEs7nltIaLCadRCh1NZrAHaEl&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.BplSTy2d47Q6j5VQou3aegHaIR&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.Jtxh-2_JwMoaOEbiYPY-0gHaFx&pid=Api&P=0&h=180",
        ],
        title: "Coco",
        age: 1,
        date: "08-04-2024",
        description:
            "Coco is a cuddly and affectionate Shih Tzu who loves lounging on laps and soaking up love. Her fluffy coat and playful nature make her the perfect indoor buddy.\n\nCoco doesn’t need much space to be happy—just a warm bed and someone to adore her. She’s ideal for first-time pet owners.",
        gender: Gender.Female,
        breed: "Shih Tzu",
        //isLiked: false,
        isPet: true,
        //price: 870,
      ),
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.zo_Otr2yraMeO4JvbojuPAHaGL&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.1purjc7M4wIb2ZADyyHVVgHaE9&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.hhaUuJ_ONGMQHuCbtMg8twHaE8&pid=Api&P=0&h=180",
        ],
        title: "Toby",
        age: 2,
        date: "22-02-2024",
        description:
            "Toby is a lively Chihuahua who is confident and charismatic. Despite his size, he isn’t afraid to take on the world—or at least guard your sofa.\n\nHe enjoys short walks, snuggling in blankets, and barking at anything suspicious. A great match for someone looking for a pocket-sized protector.",
        gender: Gender.Male,
        breed: "Chihuahua",
        //isLiked: false,
        isPet: true,
        //price: 650,
      ),
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.Xh9C2_1oujAMxyOu4Q8ZpQHaE8&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.q9AVu6WECWeQKr_cLyM_QAHaE7&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.CsvweDzJFibHgR-Ti1pEcwHaE7&pid=Api&P=0&h=180",
        ],
        title: "Molly",
        age: 3,
        date: "14-03-2024",
        description:
            "Molly is a sweet-natured Dachshund with a long body and an even longer list of cuddles to give. She’s curious, brave, and always exploring her surroundings.\n\nHer low build doesn’t stop her from being adventurous. Molly is a loyal friend who loves toys, treats, and tummy rubs.",
        gender: Gender.Female,
        breed: "Dachshund",
        //isLiked: false,
        isPet: true,
        //price: 700,
      ),
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.udEheTCMXJzVEPmhbMmVKQHaH1&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.zn3QJDqxk012ojrDmaLDjgHaE8&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.6Z83aNJVBRr038NKRRbuXgHaHa&pid=Api&P=0&h=180",
        ],
        title: "Oscar",
        age: 2,
        date: "10-03-2024",
        description:
            "Oscar is a charming French Bulldog with a playful spirit and a heart full of love. His bat-like ears and expressive eyes make him an instant favorite.\n\nHe enjoys short walks and long naps, making him perfect for apartment living. Oscar thrives on human companionship and is always ready to snuggle.",
        gender: Gender.Male,
        breed: "French Bulldog",
        //isLiked: false,
        isPet: true,
        //price: 950,
      ),
      Details(
        image: [
          "https://tse2.mm.bing.net/th?id=OIP.egc9r3pY0O91oH_iQP9v7QHaF4&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.X4XOgeQGi4YVTrH-LTuSUgHaEz&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.BZ1RXrKuSBMJNZ2TO8qHcgHaE_&pid=Api&P=0&h=180",
        ],
        title: "Sadie",
        age: 4,
        date: "05-02-2024",
        description:
            "Sadie is a strong and loyal Rottweiler who takes her role as a guardian seriously. She's protective yet affectionate with her family.\n\nWith proper training and socialization, Sadie becomes a gentle giant who enjoys playtime and cuddles. She's best suited for experienced dog owners.",
        gender: Gender.Female,
        breed: "Rottweiler",
        //isLiked: false,
        isPet: true,
        //price: 1100,
      ),
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.SaVwoFPFLL-ngj0WaHPvTAHaGf&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.nyjmhqzstu3Cf7UAyxK6ggHaH2&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.Fh2LlTLouEJc_jIMkPE-KwHaFj&pid=Api&P=0&h=180",
        ],
        title: "Zeus",
        age: 3,
        date: "28-01-2024",
        description:
            "Zeus is a majestic Siberian Husky with a striking appearance and a free spirit. He loves to run and explore, making him ideal for active owners.\n\nHis friendly nature and vocal personality make him a delightful companion. Zeus thrives in environments where he can get plenty of exercise.",
        gender: Gender.Male,
        breed: "Siberian Husky",
        //isLiked: false,
        isPet: true,
        //price: 1000,
      ),
      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.1zAWZTO8UO85e_OvDSU1iAHaFR&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.1cBwZDa7gtkkQJXknHuyVwHaE8&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.xUsAaD0nGZiDZHzPMJ0JMwHaEP&pid=Api&P=0&h=180",
        ],
        title: "Lily",
        age: 2,
        date: "12-01-2024",
        description:
            "Lily is an energetic Boxer who brings joy and laughter wherever she goes. Her playful antics and affectionate nature make her a family favorite.\n\nShe enjoys interactive games and thrives on human interaction. Lily is best suited for families who can match her energy levels.",
        gender: Gender.Female,
        breed: "Boxer",
        //isLiked: false,
        isPet: true,
        //price: 950,
      ),
      Details(
        image: [
          "https://tse2.mm.bing.net/th?id=OIP.0z6emec1UTSNO-8Lgw4oIwHaG1&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.AWq5YgQ3XbfNObqKPKHVBwHaEN&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.xhhvEM6dn7jBqfmi8xay9wAAAA&pid=Api&P=0&h=180",
        ],
        title: "Duke",
        age: 5,
        date: "20-12-2023",
        description:
            "Duke is a gentle Great Dane with a towering presence and a heart of gold. Despite his size, he's known for his calm and friendly demeanor.\n\nHe enjoys lounging around and being close to his family. Duke is perfect for those who have ample space and a love for big dogs.",
        gender: Gender.Male,
        breed: "Great Dane",
        //isLiked: false,
        isPet: true,
        //price: 1200,
      ),
      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.RdmTeN5KC7lV-zDxojn2NQHaFX&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.SBEJpR6dbnI2AVpJgObRugHaHa&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.6f7TROSXNB55pQO7FF9vYAHaFc&pid=Api&P=0&h=180",
        ],
        title: "Ginger",
        age: 1,
        date: "15-12-2023",
        description:
            "Ginger is a fluffy Pomeranian with a lively personality. She's always on the move, exploring her surroundings with curiosity.\n\nHer small size makes her ideal for apartment living, and her affectionate nature ensures she's always close to her humans.",
        gender: Gender.Female,
        breed: "Pomeranian",
        //isLiked: false,
        isPet: true,
        //price: 1200,
      ),

      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.bSPVBKQbux6a7AUkeRREZAHaEZ&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.YDHHFQ_q0HfhpAWFYKNISwHaFj&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.XP6IYH4XwiC1i-ETwPph7AHaFz&pid=Api&P=0&h=180",
        ],
        title: "Winston",
        age: 2,
        date: "15-03-2024",
        description:
            "Winston is a spirited Pembroke Welsh Corgi with a heart full of joy and energy. He’s always ready to run across the yard or play fetch with endless enthusiasm. Despite his short stature, he carries himself with regal confidence and pride.\n\nLoyal to the core, Winston bonds deeply with his human family. He loves belly rubs and curling up next to your feet after a playful day. If you’re looking for a charming companion with personality and cuteness overload, Winston is the one.",
        gender: Gender.Male,
        breed: "Pembroke Welsh Corgi",
        //isLiked: false,
        isPet: true,
        //price: 950,
      ),
      Details(
        image: [
          "https://tse2.mm.bing.net/th?id=OIP.vElp9nUAO_fzRy2CqoSw3wHaFj&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.RYcHP1AZb8KDQCaq-cExkQHaHa&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.unQkRzw7iJ8VdDZDHlPM3gHaLH&pid=Api&P=0&h=180",
        ],
        title: "Skye",
        age: 3,
        date: "10-02-2024",
        description:
            "Skye is an intelligent Australian Shepherd with boundless energy and a dazzling blue merle coat. She’s a natural at agility games and thrives on tasks that challenge her quick mind. Her bright eyes always seem to be calculating her next move.\n\nA loyal herder by instinct, Skye is deeply attached to her family and makes an excellent watchdog. With enough mental stimulation and daily exercise, she becomes the perfect active companion for outdoor enthusiasts or families who enjoy adventure.",
        gender: Gender.Female,
        breed: "Australian Shepherd",
        //isLiked: false,
        isPet: true,
        //price: 1050,
      ),
      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.nMeVBjJUB--aV9j8pZ4BVQHaFw&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.VZ4t94QX91DNDRBhswRLwAHaFT&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.CcVb0BIWMCjM5xKdr6yn5AHaHa&pid=Api&P=0&h=180",
        ],
        title: "Oliver",
        age: 4,
        date: "05-01-2024",
        description:
            "Oliver is a gentle and affectionate Cavalier King Charles Spaniel, known for his kind eyes and graceful demeanor. Whether it's lounging on your lap or enjoying a peaceful stroll, Oliver is content simply being near his humans.\n\nHis silky coat and aristocratic charm make him a favorite among those who appreciate elegance in a pet. Oliver is particularly good with children and elderly owners, offering steady companionship and plenty of cuddles.",
        gender: Gender.Male,
        breed: "Cavalier King Charles Spaniel",
        //isLiked: false,
        isPet: true,
        //price: 980,
      ),
      Details(
        image: [
          "https://tse2.mm.bing.net/th?id=OIP.3W63HV2yD8VHutAfHEaiEAHaE6&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.AKfaNVeibOuMzKtrs9xclAHaHz&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.t2Uj6cYiNl3dHP8mEb2LqwHaFI&pid=Api&P=0&h=180",
        ],
        title: "Athena",
        age: 3,
        date: "20-12-2023",
        description:
            "Athena is a sleek and powerful Doberman Pinscher, alert and intelligent. She has a graceful build and a fearless heart, always standing protectively between her loved ones and danger. Her strong instincts make her an excellent guardian.\n\nDespite her tough exterior, Athena is affectionate and gentle with her family. She thrives with structured training and is happiest when given a purpose. If you’re seeking a loyal protector with brains and beauty, Athena is your girl.",
        gender: Gender.Female,
        breed: "Doberman Pinscher",
        //isLiked: false,
        isPet: true,
        //price: 1150,
      ),
      Details(
        image: [
          "https://tse2.mm.bing.net/th?id=OIP.S_zynanXK4--FB55pLDlXAHaEc&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.1GCmLECcgzqVctuHmFgMDwHaE6&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.rfnblKW0kucOyWzEi9WfMgHaFz&pid=Api&P=0&h=180",
        ],
        title: "Bear",
        age: 5,
        date: "25-11-2023",
        description:
            "Bear is a gentle giant among dogs. This Bernese Mountain Dog is the definition of calm and composed. His thick, tricolored coat and expressive eyes make him look noble, and his temperament is just as warm as his appearance.\n\nBear enjoys cool climates, lazy afternoons, and is incredibly patient with children. He’s a perfect blend of affectionate and protective—a loyal family dog who brings joy and security wherever he goes.",
        gender: Gender.Male,
        breed: "Bernese Mountain Dog",
        //isLiked: false,
        isPet: true,
        //price: 1200,
      ),
      Details(
        image: [
          "https://tse1.mm.bing.net/th?id=OIP.9p3rEiVzKiG7rH74i8BKhgHaE8&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.o8KV1Lrt-uJhZa8jafWDQwHaFj&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.JffooVFD6zc3ISB4alWM5gHaFj&pid=Api&P=0&h=180",
        ],
        title: "Lola",
        age: 2,
        date: "10-10-2023",
        description:
            "Lola is a playful Boston Terrier with a tuxedo-like coat and a lively spirit. Always cheerful, she makes friends quickly and spreads joy everywhere she goes. She’s compact, adaptable, and perfect for apartment living.\n\nHer small size doesn’t stop her from being a bundle of energy. Lola loves fetching, learning tricks, and being the center of attention. She’s a true entertainer and an affectionate lap dog rolled into one.",
        gender: Gender.Female,
        breed: "Boston Terrier",
        //isLiked: false,
        isPet: true,
        //price: 850,
      ),
      Details(
        image: [
          "https://tse1.mm.bing.net/th?id=OIP.5OCL4YdckaiXqsKuZr654gHaE6&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.6Sik0vlKcfoPiSo4kjnYXAHaFj&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.uwmmEVtk5YQO4PSXVcPVaQHaFw&pid=Api&P=0&h=180",
        ],
        title: "Milo",
        age: 1,
        date: "05-09-2023",
        description:
            "Milo is a delightful Havanese pup with a fluffy coat and a sparkle in his eye. He’s friendly to all—kids, strangers, other pets—and thrives on companionship. Milo enjoys being pampered and is always ready to greet guests with his happy dance.\n\nAs a low-shedding breed, he’s ideal for families with mild allergies. Milo is alert, smart, and loves to perform tricks for treats. He’ll fit right into a loving household that enjoys affectionate, low-maintenance dogs.",
        gender: Gender.Male,
        breed: "Havanese",
        //isLiked: false,
        isPet: true,
        //price: 900,
      ),
      Details(
        image: [
          "https://tse1.mm.bing.net/th?id=OIP.6m5ZlyN0ZT9GQ50jBoYqTQHaGa&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.g3A5d1t4qFDzvob8RbLMsAHaHa&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.HHadgM7GIRqXvqtIqVUeqQHaHa&pid=Api&P=0&h=180",
        ],
        title: "Sophie",
        age: 2,
        date: "15-08-2023",
        description:
            "Sophie is an elegant Maltese known for her cloud-white coat and calm disposition. She's sweet-natured and thrives on love and cuddles. Her small size makes her ideal for apartments, and she loves lounging by your side or being gently carried around.\n\nSophie’s hypoallergenic fur is easy to manage with regular grooming, and her charm will melt your heart. She’s perfect for anyone seeking a loyal, graceful, and elegant companion.",
        gender: Gender.Female,
        breed: "Maltese",
        //isLiked: false,
        isPet: true,
        //price: 950,
      ),
    ],
  ),
  Heading(
    title: "Cats",
    icon: "https://cdn1.iconfinder.com/data/icons/cat-supplies-line/64/cat-01-1024.png", // Add your own icon link here
    lists: [
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.W8g6rSqaqp3qG8_ovALxTwHaE6&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.5p1egKEaqvzIX8b8Ks8ghgHaDT&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.Zbxmw4HOhP9RS0yM663E2AHaE5&pid=Api&P=0&h=180",
        ],
        title: "Luna",
        age: 2,
        date: "10-02-2024",
        description: "Luna is a friendly and elegant Persian cat who enjoys cuddling and calm environments.",
        gender: Gender.Female,
        breed: "Persian",
        //isLiked: false,
        isPet: true,
        //price: 700,
      ),
      Details(
        image: [
          "https://tse1.mm.bing.net/th?id=OIP.3M0IBj0iwl2XQBaov3vC3wHaE6&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.np1J2d3E-BRupCJ5LTTQMgHaGb&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.g5u06zGyd3fYpRvLGmuXqgHaE8&pid=Api&P=0&h=180",
        ],
        title: "Leo",
        age: 1,
        date: "21-03-2024",
        description: "Leo is a playful and social Maine Coon, perfect for families and active homes.",
        gender: Gender.Male,
        breed: "Maine Coon",
        //isLiked: false,
        isPet: true,
        //price: 800,
      ),
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.hYfhMpIRg20WebD8RlpTmgHaE7&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.QSgvkV_B7bJq6s-jixI2CAHaFj&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.zJFurL_oC5ED1pzthTHTRgHaLH&pid=Api&P=0&h=180",
        ],
        title: "Milo",
        age: 3,
        date: "05-01-2024",
        description: "Milo is a curious and talkative Siamese cat with striking blue eyes.",
        gender: Gender.Male,
        breed: "Siamese",
        //isLiked: false,
        isPet: true,
        //price: 750,
      ),
      Details(
        image: [
          "https://tse1.mm.bing.net/th?id=OIP.bHarRW7CDYimM3cUGf6y5QHaE7&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.nA9Yl_fwx_V2BZ5kw050nAHaFj&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.j1xJiLlBuPwjQq3D4eRDPwHaD8&pid=Api&P=0&h=180",
        ],
        title: "Chloe",
        age: 2,
        date: "17-03-2024",
        description: "Chloe is a gentle and affectionate Ragdoll with a fluffy coat and calm temperament.",
        gender: Gender.Female,
        breed: "Ragdoll",
        //isLiked: false,
        isPet: true,
        //price: 850,
      ),
      Details(
        image: [
          "https://tse2.mm.bing.net/th?id=OIP.m5GIUH1WQcj_uvQtnxOFXAHaFV&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.0P6sLGmicIG2pdpUNbSbuwHaF2&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.ELMUZmynV-upC9CBGYbzkwHaE8&pid=Api&P=0&h=180",
        ],
        title: "Oreo",
        age: 1,
        date: "30-03-2024",
        description: "Oreo is a mischievous and energetic Bengal cat with stunning markings.",
        gender: Gender.Male,
        breed: "Bengal",
        //isLiked: false,
        isPet: true,
        //price: 950,
      ),
      Details(
        image: [
          "https://tse1.mm.bing.net/th?id=OIP.480BdO4sF_wi-Ky6qmMzuAHaFh&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.VJeyAQn66BXOojyKoxvw2QHaFX&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.H92MUM5N0Ny5ZO0XIwtbwwHaE8&pid=Api&P=0&h=180",
        ],
        title: "Nala",
        age: 2,
        date: "12-02-2024",
        description: "Nala is a Scottish Fold with adorable folded ears and a sweet nature.",
        gender: Gender.Female,
        breed: "Scottish Fold",
        //isLiked: false,
        isPet: true,
        //price: 720,
      ),
      Details(
        image: [
          "https://tse2.mm.bing.net/th?id=OIP.BHFcVvoT2TOsJ34i351v3gHaEt&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.h40syMX7GOk9FKel5oFtcgHaE8&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.Xri8JmiwDEeX9hLC1grvJQHaIQ&pid=Api&P=0&h=180",
        ],
        title: "Simba",
        age: 1,
        date: "11-01-2024",
        description: "Simba is an energetic Abyssinian who loves to explore and play.",
        gender: Gender.Male,
        breed: "Abyssinian",
        //isLiked: false,
        isPet: true,
        //price: 680,
      ),
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP._2hkVdqgk9deObKqKrQdcwHaNT&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.07wi8LQZ_AZtxQG_1EO9awHaJ4&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.idKx-XEaKLEx7F-7inpfdQHaH_&pid=Api&P=0&h=180",
        ],
        title: "Cleo",
        age: 3,
        date: "01-01-2024",
        description: "Cleo is a calm and graceful Russian Blue with a silvery coat and shy demeanor.",
        gender: Gender.Female,
        breed: "Russian Blue",
        //isLiked: false,
        isPet: true,
        //price: 770,
      ),
      Details(
        image: [
          "https://tse2.mm.bing.net/th?id=OIP._jUh-8T_6S9mjvf49R_ZrwHaEo&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.sr0KcoBByChukFVeNlnrPgHaHa&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.rAHtguX-8K7QivbGqw-nFQHaE8&pid=Api&P=0&h=180",
        ],
        title: "Rocky",
        age: 2,
        date: "28-02-2024",
        description: "Rocky is a playful and intelligent American Shorthair who adapts well to any home.",
        gender: Gender.Male,
        breed: "American Shorthair",
        //isLiked: false,
        isPet: true,
        //price: 600,
      ),
      Details(
        image: [
          "https://tse1.mm.bing.net/th?id=OIP.HPX413K2eyeMU9hezYJ4ygHaEK&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.gydJUtCqC6TKMJTTBZ-KNgHaEJ&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.9oowkWRlitOcUo4zoEBLegHaEx&pid=Api&P=0&h=180",
        ],
        title: "Zoe",
        age: 2,
        date: "18-03-2024",
        description: "Zoe is a gentle and beautiful Birman with striking blue eyes and white paws.",
        gender: Gender.Female,
        breed: "Birman",
        //isLiked: false,
        isPet: true,
        //price: 690,
      ),
      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.m-oQKg1eASmSfdGZVVS5hAHaLQ&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.Xt8aVJqA5xAvzNGDDE3l6QHaGX&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.CmfIGlNIVCM7n1n9my2_owHaHa&pid=Api&P=0&h=180",
        ],
        title: "Toby",
        age: 1,
        date: "10-03-2024",
        description: "Toby is a fun-loving Sphynx who enjoys human attention and has a warm personality.",
        gender: Gender.Male,
        breed: "Sphynx",
        //isLiked: false,
        isPet: true,
        //price: 1000,
      ),
      Details(
        image: [
          "https://tse2.mm.bing.net/th?id=OIP.JgGeW6D2XdIEx5iFxY1AmgHaE8&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.EJ9NoO74DWc5FLJwMFfp5wHaFj&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.BfFCvsDPNB_-V7Fvc1pbwAHaF0&pid=Api&P=0&h=180",
        ],
        title: "Lily",
        age: 3,
        date: "04-01-2024",
        description: "Lily is an exotic Shorthair with a plush coat and affectionate temperament.",
        gender: Gender.Female,
        breed: "Siberian",
        //isLiked: false,
        isPet: true,
        //price: 880,
      ),
      Details(
        image: [
          "https://tse1.mm.bing.net/th?id=OIP.Wdl8KXy90ATtR2ovw0MzTAHaF2&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.3w3BDr3QIzCLPjjtl_dBRwHaEK&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.HP8nzSasVHeGTXe3wALvTgHaEy&pid=Api&P=0&h=180",
        ],
        title: "Felix",
        age: 2,
        date: "22-03-2024",
        description: "Felix is a Manx cat known for his playful nature and lack of tail.",
        gender: Gender.Male,
        breed: "Manx",
        //isLiked: false,
        isPet: true,
        //price: 620,
      ),
      Details(
        image: [
          "https://tse2.mm.bing.net/th?id=OIP.QGmnG2AyaQ6qTZIG22wUBwHaEK&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.0mP5FTyTj0FuLJWbGxkL2QHaFG&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.Df4Fs8u-dD5atgUL6cMXwwHaHa&pid=Api&P=0&h=180",
        ],
        title: "Bella",
        age: 1,
        date: "26-02-2024",
        description: "Bella is a charming Chartreux with a woolly coat and mellow personality.",
        gender: Gender.Female,
        breed: "Chartreux",
        //isLiked: false,
        isPet: true,
        //price: 700,
      ),
      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.liLrWzvCUdAAhquZdIXjTwHaE8&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.Lak_0UQSMgm6OgAVHWfalAHaE8&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.8KJ7fpiLM-jIFYvn_uVGCwHaLG&pid=Api&P=0&h=180",
        ],
        title: "Tiger",
        age: 2,
        date: "15-02-2024",
        description: "Tiger is an adventurous Ocicat who resembles a wild cat but is very loving.",
        gender: Gender.Male,
        breed: "Ocicat",
        //isLiked: false,
        isPet: true,
        //price: 780,
      ),
      Details(
        image: [
          "https://tse1.mm.bing.net/th?id=OIP.9W5L-Jml8FvEOCHMlUXKVQHaE8&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.MWaz0jTfykQckwl3ojuE3AHaD2&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.ucWFmHZq2vE4KlUcTp_M7gHaE7&pid=Api&P=0&h=180",
        ],
        title: "Misty",
        age: 3,
        date: "03-01-2024",
        description: "Misty is a Norwegian Forest Cat with a thick coat and gentle nature.",
        gender: Gender.Female,
        breed: "Norwegian Forest Cat",
        //isLiked: false,
        isPet: true,
        //price: 810,
      ),
      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.7FOPu4ExFXfL9fFnapb0CwHaE8&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.f5L3aybxRyOTTxuRkrUhYgHaHa&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.WjEpVjrXB5_hV1iUln1TvAHaLH&pid=Api&P=0&h=180",
        ],
        title: "Shadow",
        age: 1,
        date: "05-04-2024",
        description: "Shadow is a sleek Bombay cat known for its glossy black coat and affectionate behavior.",
        gender: Gender.Male,
        breed: "Bombay",
        //isLiked: false,
        isPet: true,
        //price: 660,
      ),
      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.cOxgspGvq4lGIrl7gEHnQwHaFj&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.h3MtemqsiEGXvw6fgJtxMwHaFf&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.bTP0pNxcCqiZR0wF9MOnFgHaFM&pid=Api&P=0&h=180",
        ],
        title: "Ruby",
        age: 2,
        date: "07-02-2024",
        description: "Ruby is a Cornish Rex with soft fur and an energetic, acrobatic personality.",
        gender: Gender.Female,
        breed: "Cornish Rex",
        //isLiked: false,
        isPet: true,
        //price: 740,
      ),
      Details(
        image: [
          "https://tse1.mm.bing.net/th?id=OIP.SjS5haa7TJFN1Dxlzc4D8QHaFT&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.YqqhPgDybDd3sjR09ouPLQHaLc&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.lTJC4PYYQCgF11uQdCYBJQHaFw&pid=Api&P=0&h=180",
        ],
        title: "Max",
        age: 1,
        date: "02-03-2024",
        description: "Max is a Tonkinese cat who is social, affectionate, and loves being around people.",
        gender: Gender.Male,
        breed: "Tonkinese",
        //isLiked: false,
        isPet: true,
        //price: 710,
      ),
      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.-RapkWUuqV3PCKc_U95WFAHaEw&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.cQAKQgHD4vOJUuW2lmkr6gHaFM&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.HOW820pcDUkMYcIbkarzyAHaFP&pid=Api&P=0&h=180",
        ],
        title: "Daisy",
        age: 2,
        date: "10-01-2024",
        description: "Daisy is a loving and playful Burmese cat with a silky coat and big eyes.",
        gender: Gender.Female,
        breed: "Burmese",
        //isLiked: false,
        isPet: true,
        //price: 720,
      ),
      Details(
        image: [
          "https://tse1.mm.bing.net/th?id=OIP.lVudIoVk98NBeYYloZKSQAHaIc&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.7JvGTEk_N92kT6XR7sCowQHaFj&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.9-9jCpnBkCrhUsACvb6kMgHaIA&pid=Api&P=0&h=180",
        ],
        title: "Oliver",
        age: 1,
        date: "25-02-2024",
        description: "Oliver is an Egyptian Mau with a spotted coat and incredible speed and agility.",
        gender: Gender.Male,
        breed: "Egyptian Mau",
        //isLiked: false,
        isPet: true,
        //price: 930,
      ),
      Details(
        image: [
          "https://tse2.mm.bing.net/th?id=OIP.MHYvqOsfundr4MOIxX6_xQHaE8&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.Syn7hM0GMLlqzfz642KtLgHaEx&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.H33XyzT5vAESaGTU6iUtngHaE8&pid=Api&P=0&h=180",
        ],
        title: "Sasha",
        age: 3,
        date: "13-03-2024",
        description: "Sasha is a Singapura, the smallest cat breed, full of energy and charm.",
        gender: Gender.Female,
        breed: "Singapura",
        //isLiked: false,
        isPet: true,
        //price: 940,
      ),
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.pDGvBvEk3CP5eyqE0SLYXwHaEX&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.ouQyNzal7xzjCgT8IrfnJgHaFj&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.6cNNNd1I6bm9XqxEYCZTaQHaEX&pid=Api&P=0&h=180",
        ],
        title: "Buddy",
        age: 2,
        date: "08-01-2024",
        description: "Buddy is a Japanese Bobtail with a short, puffy tail and friendly attitude.",
        gender: Gender.Male,
        breed: "Japanese Bobtail",
        //isLiked: false,
        isPet: true,
        //price: 790,
      ),
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.y8ffWELlHGP26JTfwrjF7wHaE8&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.hUsiOBHWc6HFlPDMLgSewgHaE8&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.JWpUKFCUe7KlNBGM0Z8r9QHaNK&pid=Api&P=0&h=180",
        ],
        title: "Peaches",
        age: 1,
        date: "19-02-2024",
        description: "Peaches is a Turkish Angora with a graceful appearance and a silky coat.",
        gender: Gender.Female,
        breed: "Turkish Angora",
        //isLiked: false,
        isPet: true,
        //price: 760,
      ),
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.UCdLOMja6XTq6glSVpf96gHaE7&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.up3iDQ2fQu1qPcR8Be6EaAHaD1&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.fRAQV-1YERH-1C8pvXU7UAHaFW&pid=Api&P=0&h=180",
        ],
        title: "Finn",
        age: 2,
        date: "06-03-2024",
        description: "Finn is a LaPerm with soft curly fur and a loving, outgoing personality.",
        gender: Gender.Male,
        breed: "LaPerm",
        //isLiked: false,
        isPet: true,
        //price: 670,
      ),
    ],
  ),
  Heading(
    title: "Birds",
    icon: "https://cdn3.iconfinder.com/data/icons/nature-animals/512/Bird-1024.png",
    lists: [
      Details(
        image: [
          "https://tse1.mm.bing.net/th?id=OIP.-WRUC2kQJS_O9z6YYsZhOQHaJ4&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.Hk4qqzN-vdjxmDL87FejcAHaJ4&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.RW_W25Nci5aW_IQwdZDKfAHaHa&pid=Api&P=0&h=180",
        ],
        title: 'Sunny',
        age: 1,
        date: '2024-06-15',
        description: 'A cheerful Sun Conure who loves music and being around people.',
        gender: Gender.Female,
        breed: 'Sun Conure',
        //isLiked: false,
        isPet: true,
        //price: 300,
      ),
      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.2p4xiZj5Jb0UPQoXi_-z-wHaIT&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP._KKLZDxssNzMXP8SHFeuuwHaFj&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.__hauTfRyv16iKOPN-nl4AHaE7&pid=Api&P=0&h=180",
        ],
        title: 'Rio',
        age: 2,
        date: '2024-05-10',
        description: 'Energetic Amazon Parrot who enjoys whistling and mimicking sounds.',
        gender: Gender.Male,
        breed: 'Amazon Parrot',
        //isLiked: false,
        isPet: true,
        //price: 700,
      ),
      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.nlkieHuEHtVZaMnamg52RwHaEn&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.ziuWM2v9B7j3dS_Pb7qv6AAAAA&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.k68AFB148UbH21YWrAHZTgHaJS&pid=Api&P=0&h=180",
        ],
        title: 'Peachy',
        age: 1,
        date: '2024-07-01',
        description: 'Playful lovebird with a curious and friendly personality.',
        gender: Gender.Female,
        breed: 'Peach-faced Lovebird',
        //isLiked: false,
        isPet: true,
        //price: 50,
      ),
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.T0Xou4ycjVTQ7e5noGao5gHaE5&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.khTeYFcrYBbXwjD2IIObjwHaE8&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.OuV0-0wqr2pI-STPysyL_wHaE8&pid=Api&P=0&h=180",
        ],
        title: 'Zazu',
        age: 1,
        date: '2024-06-01',
        description: 'Chirpy Cockatiel who whistles tunes and loves shoulder rides.',
        gender: Gender.Male,
        breed: 'Cockatiel',
        //isLiked: false,
        isPet: true,
        //price: 80,
      ),
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.MCyZWOYJ5Usq6QbMfsQIVAHaEK&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.WsAPceG2YWjwjzXqao8JDAHaLI&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.cLIICVeWOCo3dtX_axpDZgHaIe&pid=Api&P=0&h=180",
        ],
        title: 'Sky',
        age: 1,
        date: '2024-06-20',
        description: 'Friendly Budgerigar who enjoys company and colorful toys.',
        gender: Gender.Female,
        breed: 'Budgerigar (Budgie)',
        //isLiked: false,
        isPet: true,
        //price: 25,
      ),
      Details(
        image: [
          "https://tse2.mm.bing.net/th?id=OIP.q8GkVK-dRLpTK8aCczIjEgHaIM&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.yFeWMCPp9SgPdDAop7gPYgHaKX&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.xqBRgtupkUNZc7tJxKEzeAHaHa&pid=Api&P=0&h=180",
        ],
        title: 'Echo',
        age: 3,
        date: '2024-04-28',
        description: 'Brilliant African Grey with an amazing vocabulary.',
        gender: Gender.Male,
        breed: 'African Grey Parrot',
        //isLiked: false,
        isPet: true,
        //price: 1200,
      ),
      Details(
        image: [
          "https://tse1.mm.bing.net/th?id=OIP.CmJEvsAG1yhWMcT-JsCBmQHaE8&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.pvCV7GbConaHw95UzWER-AHaF7&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.huCBoVDoftSl6ZqElmub0AHaEK&pid=Api&P=0&h=180",
        ],
        title: 'Bubbles',
        age: 3,
        date: '2024-05-30',
        description: 'Stunning Blue-and-Gold Macaw who loves attention.',
        gender: Gender.Female,
        breed: 'Blue-and-Gold Macaw',
        //isLiked: false,
        isPet: true,
        //price: 1500,
      ),
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.Mf_340eYlYnsw49gj7C46wHaFi&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.wB9g6KpGfXg5IM8vSABuCQHaHd&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.NUU_loNcvE3z8BKPFFk9fgHaHE&pid=Api&P=0&h=180",
        ],
        title: 'Pico',
        age: 1,
        date: '2024-07-02',
        description: 'Energetic White-bellied Caique with a love for climbing.',
        gender: Gender.Male,
        breed: 'White-bellied Caique',
        //isLiked: false,
        isPet: true,
        //price: 850,
      ),
      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.Grj4HjqSUj6ttnf3KAsTpgHaJ4&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.8DcoqJJ-GlLTtJQ03y2w4wHaEK&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.qlHIudTYEqDK-E8YM-0OIQHaFk&pid=Api&P=0&h=180",
        ],
        title: 'Indie',
        age: 1,
        date: '2024-05-18',
        description: 'Talkative Indian Ringneck Parakeet with a playful nature.',
        gender: Gender.Female,
        breed: 'Indian Ringneck Parakeet',
        //isLiked: false,
        isPet: true,
        //price: 200,
      ),
      Details(
        image: [
          "https://tse1.mm.bing.net/th?id=OIP.ucUJq-FgDyVJmsl-sdj3pgHaFj&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.Za-T1cL7n4kywoh7p1g5JAHaE8&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.vDZ0erQejkwanPJDSBEuxgHaHa&pid=Api&P=0&h=180",
        ],
        title: 'Fizz',
        age: 1,
        date: '2024-06-10',
        description: 'Cute Fischer’s Lovebird with a big heart and bright colors.',
        gender: Gender.Male,
        breed: 'Fischer’s Lovebird',
        //isLiked: false,
        isPet: true,
        //price: 55,
      ),
      Details(
        image: [
          "https://tse2.mm.bing.net/th?id=OIP.v2Bx-GADehSmh4xB-LB_5AHaE7&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.VTkPyjQohVmqlCjTFIJr9wHaE8&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.ejINAn5pA5-R7zfPudXA3AHaJ4&pid=Api&P=0&h=180",
        ],
        title: 'Melody',
        age: 1,
        date: '2024-07-05',
        description: 'Charming Canary with a sweet singing voice and sunny personality.',
        gender: Gender.Female,
        breed: 'Canary',
        //isLiked: false,
        isPet: true,
        //price: 40,
      ),
      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.PdaQUAQw-QGdW7GoefdbLQHaEU&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.heKeANXy0cQXcUQH-3RUqwHaFn&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.PqvbqfIUf_zG510DBHUrFAHaFI&pid=Api&P=0&h=180",
        ],
        title: 'Ziggy',
        age: 1,
        date: '2024-06-28',
        description: 'Adorable Zebra Finch who chirps joyfully throughout the day.',
        gender: Gender.Male,
        breed: 'Zebra Finch',
        //isLiked: false,
        isPet: true,
        //price: 20,
      ),
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.m0Funy_E9-FPt4r7V__nqAHaGG&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.txLa1KKicKrgmf3rDlgp5gHaFj&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.5W_9h6aYYqALJvYv0VN1ZwHaHA&pid=Api&P=0&h=180",
        ],
        title: 'Olive',
        age: 1,
        date: '2024-05-22',
        description: 'Tiny but mighty Pacific Parrotlet with a brave heart.',
        gender: Gender.Female,
        breed: 'Pacific Parrotlet',
        //isLiked: false,
        isPet: true,
        //price: 150,
      ),
      Details(
        image: [
          "https://tse2.mm.bing.net/th?id=OIP.tTkAd1O0fTK4uUlO6FLZjAHaHa&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP._LolxvrxEfAjON96vCA39AHaE8&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.VRL9RLYieIqvsO7H9A_CIgHaFj&pid=Api&P=0&h=180",
        ],
        title: 'Shadow',
        age: 2,
        date: '2024-06-12',
        description: 'Quiet and gentle Blue-headed Pionus who enjoys calm settings.',
        gender: Gender.Male,
        breed: 'Blue-headed Pionus',
        //isLiked: false,
        isPet: true,
        //price: 600,
      ),
      Details(
        image: [
          "https://tse2.mm.bing.net/th?id=OIP.V54vtdO1diRBK4AMejsQmgHaGc&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.nHQz4gVf8t2EnN4_rosLUgHaE_&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.Jy9aGhk4Wt0bzrDXFC36mAHaLN&pid=Api&P=0&h=180",
        ],
        title: 'Snowy',
        age: 4,
        date: '2024-04-30',
        description: 'Affectionate Umbrella Cockatoo who loves cuddles and playtime.',
        gender: Gender.Female,
        breed: 'Umbrella Cockatoo',
        //isLiked: false,
        isPet: true,
        //price: 1600,
      ),
    ],
  ),
  Heading(
    title: "Fish",
    icon: "https://cdn0.iconfinder.com/data/icons/cosmo-medicine/40/fish-1024.png", // Add your own icon link here
    lists: [
      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.LuSCJBUiDgIwSPccmJGX7wHaFR&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.rjkj5fhNWRI7WoW0MgfbRgHaFs&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.tyUGwvCEtx0nEmuJTvkc6gHaHa&pid=Api&P=0&h=180",
        ],
        title: 'Blaze',
        age: 1,
        date: '2024-06-01',
        description: 'Colorful and active Betta fish with a feisty personality.',
        gender: Gender.Male,
        breed: 'Betta',
        //isLiked: false,
        isPet: true,
        //price: 150,
      ),
      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.PRLJdeqjZqzUGSFF_7NbpwHaFn&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.V8SdbccUQjiEuSTdD7jCKQHaEb&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.4dfbUIIUmEaFkn-WQLAahAHaE8&pid=Api&P=0&h=180",
        ],
        title: 'Goldie',
        age: 1,
        date: '2024-05-10',
        description: 'Classic and peaceful Goldfish, perfect for beginners.',
        gender: Gender.Female,
        breed: 'Goldfish',
        //isLiked: false,
        isPet: true,
        //price: 100,
      ),
      Details(
        image: [
          "https://tse1.mm.bing.net/th?id=OIP.WuzxF-hxIcIm_XjN3luDeQHaE8&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.yJKfWNRNqYw8Jh8VvvlzjwHaE7&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.I_xmCWNBmfOel1GIZjRLFwHaEL&pid=Api&P=0&h=180",
        ],
        title: 'Spark',
        age: 1,
        date: '2024-07-01',
        description: 'Vibrant and easygoing Guppy, thrives in community tanks.',
        gender: Gender.Male,
        breed: 'Guppy',
        //isLiked: false,
        isPet: true,
        //price: 40,
      ),
      Details(
        image: [
          "https://tse2.mm.bing.net/th?id=OIP.gH9btAN6E8e81jrWibur3gHaJS&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.vhAhpjf9om6LbdrZM9fP7wHaHa&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.vP4GYePcd8H-cdyrzI-zwAHaFF&pid=Api&P=0&h=180",
        ],
        title: 'Angel',
        age: 1,
        date: '2024-06-15',
        description: 'Elegant freshwater Angelfish with a graceful swim.',
        gender: Gender.Female,
        breed: 'Angelfish',
        //isLiked: false,
        isPet: true,
        //price: 200,
      ),
      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.0VC4GMrCBSgQss_KL8P5EgHaE6&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.IYrax6qdOe2hT9gI6VTe5wHaEn&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.jOSUQEnHSVbT3C6FIma5fwHaEo&pid=Api&P=0&h=180",
        ],
        title: 'Shadow',
        age: 1,
        date: '2024-06-20',
        description: 'Hardy and peaceful Molly, ideal for community aquariums.',
        gender: Gender.Male,
        breed: 'Molly',
        //isLiked: false,
        isPet: true,
        //price: 50,
      ),
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.rAixZAesWr5Z_pWHYmIlBAHaE6&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.0WMlGaWSYy8Mzo52eu_eIAHaE8&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.NKlv7VlsUJd-OuG245lBWwHaEP&pid=Api&P=0&h=180",
        ],
        title: 'Neon',
        age: 1,
        date: '2024-05-25',
        description: 'Tiny Neon Tetra with glowing colors and peaceful nature.',
        gender: Gender.Female,
        breed: 'Neon Tetra',
        //isLiked: false,
        isPet: true,
        //price: 30,
      ),
      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.-t2dBtHbIjb0l8tQKBzqJwHaEf&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.SpWnp80uxK2igKbacYymZwHaE7&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.7tg-YchJc_9BNFrtylnIuQHaE8&pid=Api&P=0&h=180",
        ],
        title: 'Tank',
        age: 2,
        date: '2024-04-28',
        description: 'Majestic and intelligent Oscar fish with a bold attitude.',
        gender: Gender.Male,
        breed: 'Oscar',
        //isLiked: false,
        isPet: true,
        //price: 500,
      ),
      Details(
        image: [
          "https://tse1.mm.bing.net/th?id=OIP.Z2H5ny2W3gHJWDL1bKlkqAHaE9&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.RCXhv9ykKyymi2IwzayZbQHaER&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.Z73Wb-O-I06dP0N8YeOZKwHaGa&pid=Api&P=0&h=180",
        ],
        title: 'Flame',
        age: 1,
        date: '2024-06-05',
        description: 'Colorful Platy fish, perfect for peaceful aquariums.',
        gender: Gender.Female,
        breed: 'Platy',
        //isLiked: false,
        isPet: true,
        //price: 35,
      ),
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.JRhJiv4WV2Yvls6p-3lXHQHaHa&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.JRhJiv4WV2Yvls6p-3lXHQHaHa&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.WWAevG8rnDHwTuKZiCfTnAHaGe&pid=Api&P=0&h=180",
        ],
        title: 'Royal',
        age: 1,
        date: '2024-05-12',
        description: 'Beautiful Discus fish with vibrant patterns, aquarium royalty.',
        gender: Gender.Male,
        breed: 'Discus',
        //isLiked: false,
        isPet: true,
        //price: 1200,
      ),
      Details(
        image: [
          "https://tse2.mm.bing.net/th?id=OIP.KdxYJzubBB-YZKzpm1YWxgHaE8&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.Nue2z_PyXfyJdQYLE6LhigHaFG&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.oNZIBhX_rsrjl2448u1zsQHaE8&pid=Api&P=0&h=180",
        ],
        title: 'Pearlie',
        age: 10,
        date: '2024-06-10',
        description: 'Peaceful Pearl Gourami with a shimmering body.',
        gender: Gender.Female,
        breed: 'Pearl Gourami',
        //isLiked: false,
        isPet: true,
        //price: 150,
      ),
      Details(
        image: [
          "https://tse2.mm.bing.net/th?id=OIP.TZ4M9i2QdnbOmHVnVDtsVwHaGe&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.X1XWuG0mGalYYbt2b2KHmwHaDo&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.PmAsm6OOON1kVDDjfUethQHaEK&pid=Api&P=0&h=180",
        ],
        title: 'Slinky',
        age: 1,
        date: '2024-05-30',
        description: 'Cute Kuhli Loach with a playful and shy nature.',
        gender: Gender.Male,
        breed: 'Kuhli Loach',
        //isLiked: false,
        isPet: true,
        //price: 90,
      ),
      Details(
        image: [
          "https://tse2.mm.bing.net/th?id=OIP.Q7Ydc1JnsozWUP4jBmjmAgHaE8&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.DALRLF4_nq-nyWMA_AmmqAHaE3&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.lkJ1hSTDcoNGz_8oOxMBvwHaE8&pid=Api&P=0&h=180",
        ],
        title: 'Benny',
        age: 1,
        date: '2024-06-18',
        description: 'Bottom-dwelling Corydoras who loves cleaning and exploring.',
        gender: Gender.Female,
        breed: 'Corydoras Catfish',
        //isLiked: false,
        isPet: true,
        //price: 60,
      ),
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.cDdzMrGwVYXF1A0gICdc8AHaE7&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.UIWesK6WHK0kzZw5BlMOAwHaE7&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.2Ua3Mv382t1RF_EDEs18hQHaEm&pid=Api&P=0&h=180",
        ],
        title: 'Sucker',
        age: 2,
        date: '2024-05-01',
        description: 'Algae-eating Pleco who keeps tanks clean and healthy.',
        gender: Gender.Male,
        breed: 'Plecostomus',
        //isLiked: false,
        isPet: true,
        //price: 250,
      ),
      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.CQUoiWb1h9hLZR1ptXr1FAHaDV&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.qgwcimo7UPP6UuJEMS-dvwHaE7&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.V1VrCJuKboJm88bj-me8tAHaFs&pid=Api&P=0&h=180",
        ],
        title: 'Rainbow',
        age: 1,
        date: '2024-06-22',
        description: 'Bright and colorful Rainbowfish that adds spark to any tank.',
        gender: Gender.Female,
        breed: 'Rainbowfish',
        //isLiked: false,
        isPet: true,
        //price: 130,
      ),
    ],
  ),
  Heading(
    title: "Others",
    icon: "https://icon-library.com/images/pet-icon-png/pet-icon-png-7.jpg",
    lists: [
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.xc5GYWilfaxUcDawwru3wwHaE7&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.50qSkebUKsv5ceMOC4a8nQHaE7&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.ViQ7C2HGuvQcOBto4M-5IgHaE7&pid=Api&P=0&h=180",
        ],
        title: "Bunny Coco",
        age: 10,
        date: "04-05-2025",
        description:
            "Bunny Coco is an adorable Holland Lop rabbit, known for her floppy ears and gentle personality. She’s a quiet and affectionate companion who thrives in calm indoor environments. Her soft fur and small size make her ideal for cuddling, and she loves nibbling on veggies and hopping around during playtime.\n\nHolland Lops are low-maintenance and easy to bond with, making them perfect for both individuals and families.",
        gender: Gender.Female,
        breed: "Holland Lop Rabbit",
        //isLiked: false,
        isPet: true,
        //price: 2500,
      ),
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.1xKxMKxh4NeAr5XOmsmVQwHaGX&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.dluQkg9DhxRz1nbh8N1JSAHaHa&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.0ema91WYmufOBehVamebIwHaE5&pid=Api&P=0&h=180",
        ],
        title: "Guinea Bella",
        age: 8,
        date: "04-05-2025",
        description:
            "Guinea Bella is a lively Abyssinian guinea pig, famous for her rosette-patterned fur and social demeanor. She chirps with excitement when greeted and enjoys spending time being held or exploring her surroundings with her curious nature.\n\nAbyssinian guinea pigs are highly sociable and thrive when kept in pairs or groups. Guinea Bella is a delightful pet for families who want a cuddly and interactive furry friend.",
        gender: Gender.Female,
        breed: "Abyssinian Guinea Pig",
        //isLiked: false,
        isPet: true,
        //price: 1500,
      ),
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.kNfBwbSU9x_pXLawHyBAVAHaE8&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.FomLqlcVUYF3zd9aKLETygHaE7&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.3wzOtYpRwe24Haij4cfdUwHaE8&pid=Api&P=0&h=180",
        ],
        title: "Hammy Max",
        age: 6,
        date: "04-05-2025",
        description:
            "Hammy Max is a Syrian hamster, known for his golden-brown coat and solitary yet playful personality. He loves running on his wheel, storing treats in his cheeks, and building cozy nests out of bedding.\n\nSyrian hamsters are ideal beginner pets due to their simple care needs and entertaining behavior. Hammy Max is happiest with a spacious enclosure and a nighttime routine of exploration and fun.",
        gender: Gender.Male,
        breed: "Syrian Hamster",
        //isLiked: false,
        isPet: true,
        //price: 600,
      ),
      Details(
        image: [
          "https://tse1.mm.bing.net/th?id=OIP.lO3NIy_4TjZVPO1q8TARDgHaE8&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.Ls3yI2lSCc9AEnBDI6iIcgHaEc&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.yJPxP5i1T0duDJfUp2xxOAHaE8&pid=Api&P=0&h=180",
        ],
        title: "Shelly the Turtle",
        age: 24,
        date: "04-05-2025",
        description:
            "Shelly is a Red-Eared Slider turtle with striking red markings on the side of her head and a peaceful nature. She enjoys basking under her heat lamp and gliding through water gracefully.\n\nRed-Eared Sliders are resilient reptiles that can live for decades with proper tank care and a balanced diet. Shelly is a captivating pet, ideal for those who enjoy low-maintenance aquatic companions.",
        gender: Gender.Female,
        breed: "Red-Eared Slider",
        //isLiked: false,
        isPet: true,
        //price: 1000,
      ),
      Details(
        image: [
          "https://tse1.mm.bing.net/th?id=OIP.RrGHmMWLRoX7lt9RZai_1gHaD3&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.RjNra_w-dnPMaLKjPatyVgHaJ-&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.JOs5zb3AgpcT-ucDX-qEYAHaE7&pid=Api&P=0&h=180",
        ],
        title: "Torto Tim",
        age: 30,
        date: "04-05-2025",
        description:
            "Torto Tim is a calm Indian Star Tortoise, admired for his beautifully patterned shell and relaxed personality. He enjoys grazing on leafy greens and taking slow strolls in the sun.\n\nThese tortoises are gentle and can live for many years, often becoming lifelong companions. Torto Tim is perfect for garden-loving pet owners looking for a peaceful, terrestrial reptile.",
        gender: Gender.Male,
        breed: "Indian Star Tortoise",
        //isLiked: false,
        isPet: true,
        //price: 6000,
      ),
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.WmAiTFwIZvSio_cqALHNewHaEX&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.VnRb9rOIci6DSamILZMFVAHaD4&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.7_wH2qpj5F44hFkaaxpidAHaFQ&pid=Api&P=0&h=180",
        ],
        title: "Iggy Spike",
        age: 12,
        date: "04-05-2025",
        description:
            "Iggy Spike is a striking Green Iguana with a regal appearance and a calm, observant demeanor. With time and care, he can bond well with his owner and even learn to enjoy gentle handling.\n\nGreen Iguanas require specialized habitats and a diet rich in greens, but their unique look and intelligence make them standout exotic pets. Iggy Spike is ideal for dedicated reptile enthusiasts.",
        gender: Gender.Male,
        breed: "Green Iguana",
        //isLiked: false,
        isPet: true,
        //price: 3000,
      ),
      Details(
        image: [
          "https://tse2.mm.bing.net/th?id=OIP.56P4BsrYIqsX1HZKsQKKsAHaEc&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.JC2_CLPxiR4pXBjrn6LTpQHaFn&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.BZpmY5l9j9gVsISckSdGwgHaDv&pid=Api&P=0&h=180",
        ],
        title: "Dragon Blaze",
        age: 14,
        date: "04-05-2025",
        description:
            "Dragon Blaze is a friendly Bearded Dragon known for his expressive face and calm personality. He enjoys basking under warm light, munching on insects and veggies, and climbing decor in his terrarium.\n\nBearded Dragons are great for first-time reptile keepers due to their manageable care needs and affectionate behavior. Blaze is a curious and relaxed buddy, perfect for interactive reptile lovers.",
        gender: Gender.Male,
        breed: "Bearded Dragon",
        //isLiked: false,
        isPet: true,
        //price: 4000,
      ),
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.KasyRsrY0jrVBMEZSeIqKgHaF0&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.36odYwn5nR39eI0QJ9b4kgHaFD&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.ydNcsHSHF8k37gePkM0-EQHaDf&pid=Api&P=0&h=180",
        ],
        title: "Ferret Dash",
        age: 10,
        date: "04-05-2025",
        description:
            "Ferret Dash is a high-energy pet who loves exploring, tunneling, and playing chase. His sleek body and mischievous personality make every day an adventure.\n\nFerrets are intelligent and social, best kept in ferret-proofed homes with plenty of enrichment. Dash thrives on interaction and is great for active owners who can keep up with his antics.",
        gender: Gender.Male,
        breed: "Standard Ferret",
        //isLiked: false,
        isPet: true,
        //price: 5000,
      ),
      Details(
        image: [
          "https://tse4.mm.bing.net/th?id=OIP.-kMWcM3-s56mFHC8qh-VqgHaEM&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.b6AkYdRIurIkeIEACSdJ2gAAAA&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.34r4JHMNbjHr7hdP2YMy5AHaGa&pid=Api&P=0&h=180",
        ],
        title: "Hedgie Luna",
        age: 9,
        date: "04-05-2025",
        description:
            "Hedgie Luna is a shy but sweet African Pygmy Hedgehog with soft quills and a gentle heart. She enjoys quiet nights, exploring her enclosure, and cuddling in a cozy blanket.\n\nOnce bonded, hedgehogs like Luna are endearing companions who can be carried in hand or tucked into shirt pockets. She’s a unique and lovable nocturnal pet for calm households.",
        gender: Gender.Female,
        breed: "African Pygmy Hedgehog",
        //isLiked: false,
        isPet: true,
        //price: 2500,
      ),
      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.YWr9Eql2Ams73lKFmu1brwHaFj&pid=Api&P=0&h=180",
          "https://tse1.mm.bing.net/th?id=OIP.g220yrLaoulQHnozeg_VIAHaFG&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.a185vi7ZepqWeBghnMmqPgHaE6&pid=Api&P=0&h=180",
        ],
        title: "Chinchy Fluff",
        age: 8,
        date: "04-05-2025",
        description:
            "Chinchy Fluff is a luxurious Chinchilla with cloud-like fur and a playful, agile personality. He enjoys dust baths, jumping around on shelves, and nibbling on hay.\n\nChinchillas are clean, odor-free pets that require cool temperatures and space to jump and explore. Fluff is perfect for owners who enjoy observing active, fluff-filled fun.",
        gender: Gender.Male,
        breed: "Standard Chinchilla",
        //isLiked: false,
        isPet: true,
        //price: 4500,
      ),
      Details(
        image: [
          "https://tse2.mm.bing.net/th?id=OIP.PItN5zLxLxPxUCq7lzwn9AHaE8&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.kp3LQjw7tP7agPwG_AIbOwHaFf&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.hQeePcURXBgjWCF9_0dsBgAAAA&pid=Api&P=0&h=180",
        ],
        title: "Gerbie Nibbles",
        age: 5,
        date: "04-05-2025",
        description:
            "Gerbie Nibbles is an energetic Mongolian Gerbil who loves digging tunnels and playing with chew toys. His quick movements and social behavior make him fascinating to watch.\n\nGerbils like Nibbles do well in pairs and love to stay active. He’s an ideal pet for those seeking an entertaining, low-maintenance rodent friend.",
        gender: Gender.Male,
        breed: "Mongolian Gerbil",
        //isLiked: false,
        isPet: true,
        //price: 500,
      ),
      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.e2g1aY4ygLSABHoD7eqszQHaF2&pid=Api&P=0&h=180",
          "https://tse2.mm.bing.net/th?id=OIP.2H9dPzS__Yv_sGyt8rT9_wHaGU&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.W5MK1cnzoiTqCVApswSJ-AHaHP&pid=Api&P=0&h=180",
        ],
        title: "Glider Sky",
        age: 7,
        date: "04-05-2025",
        description:
            "Glider Sky is a nocturnal Sugar Glider who bonds deeply with her owner. She loves gliding from perch to perch and snuggling in warm bonding pouches during the day.\n\nSugar Gliders are affectionate marsupials that need companionship and a consistent routine. Sky is great for devoted owners ready to offer attention and love.",
        gender: Gender.Female,
        breed: "Sugar Glider",
        //isLiked: false,
        isPet: true,
        //price: 5500,
      ),
      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.eX4Sig3n5fqJiO96PYvgKQHaHa&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.RXaN6bsipNli8FZyXrIHdgHaE7&pid=Api&P=0&h=180",
          "https://tse4.mm.bing.net/th?id=OIP.Ui3NRYhSTqcvhUwrs5RZlAHaFj&pid=Api&P=0&h=180",
        ],
        title: "Snaily Mocha",
        age: 3,
        date: "04-05-2025",
        description:
            "Snaily Mocha is a Giant African Land Snail with a beautiful spiraled shell and calm nature. He enjoys munching on fruits and vegetables and exploring with his slow and steady pace.\n\nLow-maintenance and surprisingly charming, Mocha is a conversation-starting pet who fits perfectly into quiet homes looking for something unique.",
        gender: Gender.Male,
        breed: "Giant African Land Snail",
        //isLiked: false,
        isPet: true,
        //price: 200,
      ),
      Details(
        image: [
          "https://tse3.mm.bing.net/th?id=OIP.yyy50j0WDlYgQttCATA_vwHaFj&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.dRDz0YpWaXJonTxbPnhQKgHaE9&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.zCiO-Ckr1EvYCuwZYJ4CsgHaE8&pid=Api&P=0&h=180",
        ],
        title: "Leo Gizmo",
        age: 6,
        date: "04-05-2025",
        description:
            "Leo Gizmo is a spotted Leopard Gecko known for his friendly nature and expressive eyes. He loves hunting crickets, basking under heat, and curling up in his hideaway.\n\nLeopard Geckos are beginner-friendly reptiles with minimal care needs and great personalities. Gizmo is perfect for pet owners who enjoy handling their reptile and watching quirky behavior.",
        gender: Gender.Male,
        breed: "Leopard Gecko",
        //isLiked: false,
        isPet: true,
        //price: 1800,
      ),
      Details(
        image: [
          "https://tse1.mm.bing.net/th?id=OIP.nVuDM7ifOTm5UbSB8ep1GgHaEo&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.SK25HV3TyBQGyNpJ0VgPWAHaG1&pid=Api&P=0&h=180",
          "https://tse3.mm.bing.net/th?id=OIP.P7JtNfwcTAEElMAnpEQ5xAHaGx&pid=Api&P=0&h=180",
        ],
        title: "Majestic Friesian",
        age: 48,
        date: "04-05-2025",
        description:
            "Majestic Friesian is a stunning example of the Friesian breed, known for its black coat, flowing mane, and regal posture. He is elegant in motion and gentle in temperament, making him a favorite for parades, dressage, and film appearances.\n\nFriesians are one of the most beautiful horse breeds in the world, admired for their power, grace, and noble presence. Owning a Friesian is like owning a living piece of art and heritage.",
        gender: Gender.Male,
        breed: "Friesian Horse",
        //isLiked: false,
        isPet: true,
        //price: 850000,
      ),
    ],
  ),
];
