import 'package:pawlinker/model/heading.dart';

List<Heading> HeadingsCare = [
  Heading(
    title: 'Dog Food',
    icon: 'https://cdn-icons-png.flaticon.com/512/404/404037.png',
    lists: [
      Details(
        image: ['https://i.pinimg.com/736x/20/0d/b4/200db4e575b3e2e981bee433c4dac003.jpg'],
        title: 'High Protein Dry Kibble',
        age: 1,
        date: '2026-05-04',
        description: 'Formulated to support the healthy joints, coat, and overall vitality of Labrador Retrievers.',
        gender: Gender.Male,
        breed: 'Labrador Retriever',
        //isLiked: false,
        isPet: false,
        price: 20,
      ),
      Details(
        image: ['https://m.media-amazon.com/images/I/71R8vbImKTL.jpg'],
        title: "Hill's Science Diet Adult Large Breed Chicken & Barley Recipe",
        age: 1,
        date: '2026-05-04',
        description: 'Provides balanced nutrition for Golden Retrievers, promoting healthy skin, coat, and joint health.',
        gender: Gender.Male,
        breed: 'Golden Retriever',
        //isLiked: false,
        isPet: false,
        price: 25,
      ),
      Details(
        image: [
          'https://m.media-amazon.com/images/I/716ahBsa8oL._SY741_.jpg',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZHzECK6QRG1G_Tal-_SJTSJp_6blfyox8Ug&s',
        ],
        title: 'Blue Buffalo Life Protection Formula Adult Chicken & Brown Rice Recipe',
        age: 1,
        date: '2026-05-04',
        description: 'Ideal for German Shepherds, with real chicken and whole grains for muscle development and energy.',
        gender: Gender.Male,
        breed: 'German Shepherd',
        //isLiked: false,
        isPet: false,
        price: 22,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPPvoa5HyWfVzneHlFSxU9QxhhXOjpDN1Y6A&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT89jx-yKcyDIo_r5_XyG7MumkhN43nYQfEHQ&s',
        ],
        title: 'Royal Canin Poodle Adult',
        age: 1,
        date: '2026-05-04',
        description: 'Supports the specific needs of Poodles with a formula that promotes healthy skin and a shiny coat.',
        gender: Gender.Male,
        breed: 'Poodle (Toy, Miniature, Standard)',
        //isLiked: false,
        isPet: false,
        price: 18,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRN_USXNUVQbOzjJ6eMvYKrP4-Vbnb8iUkSXg&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCKOR7uhlQxA6T4vDouGh5d2M_E6Ep7w2IdA&s',
        ],
        title: 'Wellness CORE RawRev High-Protein, Raw-Centered',
        age: 1,
        date: '2026-05-04',
        description: "A high-protein food that supports Beagle's active lifestyle with real meat and raw, freeze-dried pieces.",
        gender: Gender.Male,
        breed: 'Beagle',
        //isLiked: false,
        isPet: false,
        price: 20,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9lejTf-nSP7xbrdKO0I6mF9q0WJG60HEt0g&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjTeHT121YIOl19TZ5fgvg5rYx4McjusDVsA&s',
        ],
        title: 'Royal Canin Yorkshire Terrier Adult',
        age: 1,
        date: '2026-05-04',
        description: 'Formulated to meet the specific needs of Yorkshire Terriers with a focus on skin and coat health.',
        gender: Gender.Male,
        breed: 'Yorkshire Terrier',
        //isLiked: false,
        isPet: false,
        price: 23,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRw4I3_Tu_GmxrCbJyX59aU3JvfEtJcxCKfQw&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShV2jO8ins6YNKw3gPsLlWEb6BCw6CNuCHdA&s',
        ],
        title: "Hill's Science Diet Adult Small Paws Chicken Recipe",
        age: 1,
        date: '2026-05-04',
        description: 'Perfect for Shih Tzus, providing small kibble with highly digestible ingredients.',
        gender: Gender.Male,
        breed: 'Shih Tzu',
        //isLiked: false,
        isPet: false,
        price: 24,
      ),
      Details(
        image: [
          'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTXJlGJAxJH_aKETx_enHPeuTWq7wsm1hrNA-ZCoFOmadMgYd4M2I_5aFqCOrTC4WFJBSyUjHA02eD7gNroI3AE_A_p0p0C71Bc4axOwzOuVdc4xaxjgZMypQ',
          'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTYaizDCaoQ1zFHVaXbiUApvKiSo4-cj8hw13mpWWIH0N0t4Rw0AgJC8VpBQhA-K1b91Q3bEaouN5MnyrY8xuLTLPHeBXf4PvlZ5lKFa8L2SXQl8LPmZfhO',
        ],
        title: 'Pedigree Small Dog Complete Nutrition Chicken & Steak',
        age: 1,
        date: '2026-05-04',
        description: 'A tasty and balanced food to meet the nutritional needs of small breeds like Chihuahuas.',
        gender: Gender.Male,
        breed: 'Chihuahua',
        //isLiked: false,
        isPet: false,
        price: 18,
      ),
      Details(
        image: [
          'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTvv3J2o0vXvsg3js-tiK-RC4isrAZdnVCu_OoNbcsZXeSAHGTlfobaFwWNjSdZulfcAWt7OhqHjZphqxSFiUuhnVjRwCON3lVr9M4EnMeDk3fhuOFDVSXa',
          'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSY4XP7pGnFezwAWWF4FXiWaDnwLc1vzVbeqAxG3foEpsvUnEfSZE_pTuaV-hEeR8snPPk7zhYSb8sfjf9J0KaXY8ceiSyqp-RxmjkENlTy31GUaz9MrKpC5A',
        ],
        title: "Hill's Science Diet Adult Active Longevity Chicken Recipe",
        age: 1,
        date: '2026-05-04',
        description: 'Supports the nutritional needs of Dachshunds with a focus on joint health and a longer lifespan.',
        gender: Gender.Male,
        breed: 'Dachshund',
        //isLiked: false,
        isPet: false,
        price: 21,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRiW3mNvpRgNMi_YuhXWL_tfOQwKk36UDjoR2NAiRhCKuMxPNJCvepiHXV60iGpadHvlTKMdIau3JlrlAp9w3HIS33plqqOO2bssiIVPxY6L4Nxn8WPfMxa',
          'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQS1kEtpQL51Ye7XMglCSdBuPC9KRd45AzF3gS1x0qIhR1V_zK-a76dAXHZUg141Jv9ZrMXsHLkVFz0fmRIKq_3oS_DXpHsGoumrXaMHdp5KQa_sK-NpWWVSw',
        ],
        title: 'Orijen Original Dry Dog Food',
        age: 1,
        date: '2026-05-04',
        description: 'Premium food for active breeds like Boxers, made with 85% poultry and fish protein.',
        gender: Gender.Male,
        breed: 'Boxer',
        //isLiked: false,
        isPet: false,
        price: 28,
      ),
      Details(
        image: [
          'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRoE2uAO3O5HwZFM8pvnDglXK58OfT7HlP0v7jSjvBT_FEEZsNN5VkEeWl85R5ndPgJ737bbwpU_HMihMIbi0Z2DC99dlWeZfh3Yj8u8I3kQWd8I9RpO8wUiQ',
          'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTeyHtIyZZ0kFpWAQ--W6PoaI1hASiDfAKLXBliE7FAjpTwiGEy6tVbcU9JVAcBZ2Tx4h3kqhN86c8nzMgDu-PWvMmkuhPEQ2WKI0ck_Z9XnsnVgJyng-HJTg',
        ],
        title: 'Small-breed sensitive kibble',
        age: 1,
        date: '2026-05-04',
        description: 'Specially formulated to meet the needs of Pomeranians with optimal protein and fat content.',
        gender: Gender.Male,
        breed: 'Pomeranian',
        //isLiked: false,
        isPet: false,
        price: 26,
      ),
      Details(
        image: [
          'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSZXxvhw3QEt1qHduc1-IsXyG5Z-TLgE3HuyqHiB2g6xF0k0Nu1t2nY7pMP6k3nk3UT54VZYwkDQDzkorgV3xz56dm5PmYRTl47lYkmJNaRU4BqmD65bYIp',
          'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTD8-KzzRFjmWCXAzYqai74jGJfYnYfNjuvCW0p-JoXXGSlba8bOd6C6kfPpPqUsUg7GzeGPsy4XOn_Z-AyUaIbz2AOzAZy7dquz-oQ7fSgSYhGj0ppPmf4',
        ],
        title: "High calorie protein mix",
        age: 1,
        date: '2026-05-04',
        description: 'Supports the muscle mass and joint health of Rottweilers with a special blend of nutrients.',
        gender: Gender.Male,
        breed: 'Rottweiler',
        //isLiked: false,
        isPet: false,
        price: 30,
      ),
      Details(
        image: [
          'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQOSkDnLFfBKiunTVo_zJiIj5RppJU6icZLFApZZXvhQFnn1oowYFO1FwxHOsOjr_njYyQWnjMXGETTbY2NIgMVNCYZyLQNYVNNgGsoOy_2cfawk5oC_rfRWg',
          "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSpFakWcQpv6ikx9IaPynoScRHbDWLc75BDEk7_wZX5fEnoOmhyOvRySR0n1Au3i2GUs0z6YgDKNgzIq6N3LUp_ofUudU4VQhiVe2Bf-Bio",
        ],
        title: "Skin and coat formula",
        age: 1,
        date: '2026-05-04',
        description: 'Ideal for Cocker Spaniels, promoting healthy skin and coat with a balanced diet.',
        gender: Gender.Male,
        breed: 'Cocker Spaniel',
        //isLiked: false,
        isPet: false,
        price: 22,
      ),
      Details(
        image: [
          'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQOSkDnLFfBKiunTVo_zJiIj5RppJU6icZLFApZZXvhQFnn1oowYFO1FwxHOsOjr_njYyQWnjMXGETTbY2NIgMVNCYZyLQNYVNNgGsoOy_2cfawk5oC_rfRWg',
          'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSpFakWcQpv6ikx9IaPynoScRHbDWLc75BDEk7_wZX5fEnoOmhyOvRySR0n1Au3i2GUs0z6YgDKNgzIq6N3LUp_ofUudU4VQhiVe2Bf-Bio',
        ],
        title: 'Skin and coat formula',
        age: 1,
        date: '2026-05-04',
        description: 'Formulated to meet the needs of French Bulldogs, focusing on digestive health and skin.',
        gender: Gender.Male,
        breed: 'French Bulldog',
        //isLiked: false,
        isPet: false,
        price: 23,
      ),
      Details(
        image: [
          'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRuPKUq64U9atLp4sWvShPDCF6OR5NLL0dw53QlZHLGOBRuzYFq6zLRNAclmE7WQ09py27ASyZZs3yqNQ3zXu8l-sk1MiKi0hRKvcti6Oc6h77QWFX7-0OjwA',
          'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSWWncE9B110d_e1Ws8lEppwAQTfitOwNUc4ay2jg021rG7evawvjzAgP7y5-WZ4WK1fUe7VZd6x8afRgMmyDppqNeIgRdhq9g0FfDEXR6lqYgiOxFmkgpi',
        ],
        title: 'Digestive care dry food',
        age: 1,
        date: '2026-05-04',
        description: 'Designed for high-energy breeds like Border Collies, with a focus on stamina and coat health.',
        gender: Gender.Male,
        breed: 'Border Collie',
        //isLiked: false,
        isPet: false,
        price: 21,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSB8oOCWF_xB3qVv8M38CoKz_kbGw0T69sTJsprUFsqTIekm6hvS2zpNYEa7s2erYaOJM_MuTa7gTMLbPCBtjE0vkhJVZTiJRXSbJlcU3VlqlWyz_FwBZB9',
          'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSfwp3eeFzQopX_aX5rpNZWDm3YcUJXAaoW8xF7UCfsxfkpdbuG2OnNoYTg0lBP9yLUSZl96Cz0JmBY31q0rwVJxy4-8Jwhg1Zw84AqMvKrIMxWaNKR-beGfw',
        ],
        title: "Hill's Science Diet Adult Sensitive Stomach & Skin Salmon Recipe",
        age: 1,
        date: '2026-05-04',
        description: 'Supports the digestive system and skin health of Siberian Huskies with easily digestible ingredients.',
        gender: Gender.Male,
        breed: 'High-fat dry food',
        //isLiked: false,
        isPet: false,
        price: 25,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSOtFzCkjnYoiwsCuANAAbpn2e6uGAu9ZBBcSNGuztV5HwO3QfrNQ1nMWmUwhiMyHIPOIqOIHE7q57mL739BN26AaGDE533P9DKVb9G0i4YM3EH-02w8JcxtQ',
          'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSOtFzCkjnYoiwsCuANAAbpn2e6uGAu9ZBBcSNGuztV5HwO3QfrNQ1nMWmUwhiMyHIPOIqOIHE7q57mL739BN26AaGDE533P9DKVb9G0i4YM3EH-02w8JcxtQ',
        ],
        title: 'Energy-rich kibble',
        age: 1,
        date: '2026-05-04',
        description: 'A nutritious formula to support the active lifestyle and health of Australian Shepherds.',
        gender: Gender.Male,
        breed: 'Australian Shepherd',
        //isLiked: false,
        isPet: false,
        price: 22,
      ),
      Details(
        image: [
          'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSEKh8qX86TXHLHB7_1M3BSfOPRtwDDJJo_zea_LC_TIrLKgEddY6aJqUGqgcgZoulYTeQrWfFyRQMvfkkk43mZUiivM9nIl6wd5Wy1CG692dyvGRyx83ba',
          'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTcmwj-CiqEQ7XBSGivBI6KJ2D_rZZOKCEHUMGFs-YFO5v0EvXrNuFFaH8R6oF8L0Qa8haL7vbmgA-3C0pg5bXIP8wdWtSnkxQbtlmS7kBIoTXJdT05BF5RbQ',
        ],
        title: 'Working breed formula',
        age: 1,
        date: '2026-05-04',
        description: 'Supports the specific needs of Great Danes with enhanced levels of nutrients for bone and joint health.',
        gender: Gender.Male,
        breed: 'Great Dane',
        //isLiked: false,
        isPet: false,
        price: 32,
      ),
      Details(
        image: [
          'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRQCiQF-lGKohamZqfaETVD9lvJH37oKcxIbDUJdXEl2YBIfTzvf0ydLQp2M_qTQtMEPrPxxZpPl5QVB9jJJY8BiwiE4qL6Vpn8lW4jK4qE723IrgaqQhne',
          'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcT0yZj7SF5pHItCgVxIUYM-J6b_aV1hHd_ixsthzt1iseHwL9MgC1YP2OFBdR4n_pfp0Jbp1TpiJ8cd1zG5zS_bLkwPIKU-IfBYbZ0lE6AxGdIgLg6koiUt',
        ],
        title: 'Giant breed support food',
        age: 1,
        date: '2026-05-04',
        description: 'Promotes healthy bones and joints for larger breeds like Dobermans with optimal calorie content.',
        gender: Gender.Male,
        breed: 'Doberman Pinscher',
        //isLiked: false,
        isPet: false,
        price: 28,
      ),
      Details(
        image: [
          'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTGO6RPf2Wv8C3aXmx7twEFU6jzAJEuDN5s4LttPy3YOd0KA6NgPRHC3h1ZS2aO3DDY81jlJptmHsiqMo6M7aO7haiBd0plel9qQHY9H78ww8zCcaKEBDWD',
          'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSeGxC45QrvlRRdMuPVzVog_LACxJYfI2V_Uv5yfoXiV2dHq0Qb_EAJpGmi1qzagCbj6vwzIhIXS55zeDz5ltVEkbPmYAEFR0YKY5q2QGMumgyHIDHbuX4Y',
        ],
        title: 'Muscle-maintenance kibble',
        age: 1,
        date: '2026-05-04',
        description: 'A high-protein formula with real meat and raw, freeze-dried pieces for the Maltese breed.',
        gender: Gender.Male,
        breed: 'Maltese',
        //isLiked: false,
        isPet: false,
        price: 25,
      ),
      Details(
        image: [
          'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRN5hL54cbaMtaliP7RuuCjby4PYsv9lurwUur8Av3xIZWZ3zSJX_XLwIfZHAfBv2wUsT85rJnbEUoA2GkUfc8zyuIPGP0v4sGKMVQ7w17Kimqu1mOd2Fl3Ew',
          'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRN5hL54cbaMtaliP7RuuCjby4PYsv9lurwUur8Av3xIZWZ3zSJX_XLwIfZHAfBv2wUsT85rJnbEUoA2GkUfc8zyuIPGP0v4sGKMVQ7w17Kimqu1mOd2Fl3Ew',
        ],
        title: 'Small breed dry mix',
        age: 1,
        date: '2026-05-04',
        description: 'Supports the nutritional needs of Cavalier King Charles Spaniels with a focus on healthy heart function.',
        gender: Gender.Male,
        breed: 'Cavalier King Charles Spaniel',
        //isLiked: false,
        isPet: false,
        price: 27,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTSS771EIZnfef-kFZ1LWTtibfDE0mcxWEnZ-XmVJWCGI1dPjga8j3sWi1zmGts6n_nx2U1Rbamc4Oq2GGu95xiDAWyNTS-btIUdeDKRMJL-oyylrK6yGjSFA',
        ],
        title: 'Sensitive stomach kibble',
        age: 1,
        date: '2026-05-04',
        description: 'Promotes optimal health and vitality for Boston Terriers with a formula that supports digestion.',
        gender: Gender.Male,
        breed: 'Boston Terrier',
        //isLiked: false,
        isPet: false,
        price: 24,
      ),
      Details(
        image: [
          'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQijt5ne-gOXG9ozPmy3J2RLV5dUWFWFhYeyBFsdap6zWeE4dWqtNCy8sy7uVo-4OBqGzLYmmM4dMtvvMm8ESqZ6kAtCtWxUAc6wrWi6u-f',
          'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSwG4TWS939q3113wSM59MHnlNA4kVf5kXJsvHPP4phNCSuW6JJviTwgcnvt-F_PUrZ_9sDbeKbgS2syXpBMFZaCn1k_Ke56lmgX_GGfX8W7dYzB9lD9q96kA',
        ],
        title: 'Flat-face breed formula',
        age: 1,
        date: '2026-05-04',
        description:
            'A great option for small breeds like Bichon Frises, with small kibble size and easily digestible ingredients.',
        gender: Gender.Male,
        breed: 'Bichon Frise',
        //isLiked: false,
        isPet: false,
        price: 22,
      ),
      Details(
        image: [
          'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQKix5SO9YBuOvwrnm2pby_EqzKzh_sIWSS5iYfpbUkgF7HNDQaP7Tk4eFYoC2wMD7QABV7UqIyJiSgEvSWQPCBfF9UyugrLiATyLKgMfEulXB1IIKBb1nD',
          'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRw5HuOI0mAGaA-JrJ0xmWE_xmwAr08rukSQ0TwB8ouTlZaQuNKGQF6dAuNaNTFfa0oo0zoi35-48ya8VGL92_Ad5CFyLUBEQ',
        ],
        title: 'Royal Canin Pembroke Welsh Corgi Adult',
        age: 1,
        date: '2026-05-04',
        description:
            'Formulated to meet the needs of Pembroke Welsh Corgis, with a focus on joint health and muscle maintenance.',
        gender: Gender.Male,
        breed: 'Pembroke Welsh Corgi',
        //isLiked: false,
        isPet: false,
        price: 26,
      ),
    ],
  ),

  Heading(
    title: 'cat Food',
    icon: 'https://vectorified.com/images/cat-food-icon-4.png',
    lists: [
      Details(
        image: [
          'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSrt11g3jI1BjKG4e6zP543gwAo8qJ5tznN6bLIsOZWP-7a6Yr28vysdXWS0QdskmWmlRUJjcsMPf0egn2ogQu2c-alMg_A6c499784TV9pR6jauU6i7zuQjb0',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8F7dupUcUvmabrOxKLr0ndqiSziHFCTRNag&s',
        ],
        title: 'Royal Canin Persian Pellet Dry Cat Food',
        age: 1,
        date: '2026-05-04',
        description: 'Formulated to support the healthy joints, coat, and overall vitality of Labrador Retrievers.',
        gender: Gender.Male,
        breed: 'Maine Coon',
        //isLiked: false,
        isPet: false,
        price: 20,
      ),
      Details(
        image: [
          'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcREDMv8grhFGmSHVy4AkngQMmv4URp0l9tG0B4rI2eaFDQ3qGajOR768HMyFealc8_02lsGnfPkzE5nFSx4gl-ddebPygqqpe-OBjNyiIikk3ntRtlrWUWe',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSRL4R9td77oScjn2TRRrIJoMx5tFazrQ2fg&s',
        ],
        title: 'Royal Canin Maine Coon Adult Dry Cat Food',
        age: 1,
        date: '2026-05-04',
        description: 'Supports heart health and bone strength in large breed cats like Maine Coons.',
        gender: Gender.Female,
        breed: 'Maine Coon',
        //isLiked: false,
        isPet: false,
        price: 1400,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSzLdlFASAlzt2fVDRUJY8QfZJ_xQB5k--jsnIDMwk6CqdwVSDJpBZPBpbeaA0Tt-FftnJy-NfkX8UvTmSCsy7RAF-c2lTapA',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4paHrYhbIjYp00hu8NHePlaw6sNvYYavk6Q&s',
        ],
        title: 'Royal Canin Siamese Breed Adult Dry Cat Food',
        age: 1,
        date: '2026-05-04',
        description: 'Designed for the lean body and sensitive digestion of Siamese cats.',
        gender: Gender.Male,
        breed: 'Siamese',
        //isLiked: false,
        isPet: false,
        price: 1300,
      ),
      Details(
        image: [
          'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTn0W1xCfERMFo2t8jR8vKuITGfsJrdTc9_SAnOL513NuGlpvSQikn9Xwr-60zCRLOm202jiQW070g_HNW1ayr76O7cMEMFBUnKmSB19dCa9GlAhu4slwsL',
          'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTArXKznKHqHKT1fcpOFNXUsiLlTw0-KsWT3FB6q6EX3oMKiUOVFwKc-x3KbQiIbLy9OcEjWGM5nVRQR-0D062q6fkt-35G0WrFSy0hqKOYB8g--uAET7z1hg',
        ],
        title: "Hill's Science Plan Sensitive Stomach & Skin Adult Cat Dry Food",
        age: 1,
        date: '2026-05-04',
        description: 'Helps support healthy bones, joints, and silky coats of Ragdoll cats.',
        gender: Gender.Female,
        breed: 'Ragdoll',
        //isLiked: false,
        isPet: false,
        price: 1350,
      ),
      Details(
        image: [
          'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcR3rOt4sz9o8tij3e_luEJZ53fVj3oUHkZbDsTNhQuUkKG8woKwbYQ_3dSOQ9-V7KQX4KqBy7YY8uk18CVQrEDxTIPmm9cMYbJ2o0a9chDljmxzj33hAZzw',
          'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTSPU2mw15Oxag8tGnIeSBi4yvmkiSPG4uigdPgP9p5A1xku5idj4oOy9ENxUeNH-zljG_LNZ9N8OAJ511ZW6a8xnVnyUbfMag9G2n4of5Mwww5FOPhoNb_4Q',
        ],
        title: 'Blue Buffalo Wilderness High Protein Grain-Free',
        age: 1,
        date: '2026-05-04',
        description: 'Tailored to meet the energy needs and digestive sensitivity of Bengals.',
        gender: Gender.Male,
        breed: 'Bengal',
        //isLiked: false,
        isPet: false,
        price: 1500,
      ),
      Details(
        image: [
          'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQouQrf8hHAGssyKtr08mLqd5hZD05up1nt35-UjXfz8gxs2TMn_GYwfyGRvArDonSoEYvhl15O50F6BLgZFfFeRToV8Ux1cqATnqsXUbb7jSBAiSmrmICCVQ',
          'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTxMaCDosdV886s7QY1gjiMMJdG-8Za9NMRlP4Cv9zEiLlHgaDgSGsN8uZNqnw4dOS-2q-hEh9KX0F3BDvqZWTNsHR9qmxW9zd17CFXQ53hFll6kJgECqKnlg',
        ],
        title: 'Royal Canin Feline Health Nutrition Digest Sensitive',
        age: 1,
        date: '2026-05-04',
        description: 'Maintains optimal weight and supports joint health in Scottish Folds.',
        gender: Gender.Female,
        breed: 'Scottish Fold',
        //isLiked: false,
        isPet: false,
        price: 1250,
      ),
      Details(
        image: [
          'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTSC65GeJizpx1RIk2R71tfFzQiPNQnK1Bcop4sDh_f6P2Z_u_WSk9lz-iOHcLmGl7Ae2ipDEo--BsNU0Ov0FBNYiCztg1HZ2QByI5B2J5aZW2oHhrud9oOiQ',
          'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRnwe3iP1hnFCuSYgXS5WUzbk1aqp_R3mYWkEwdyhZHGg8HKda85BGG0Qv4WGRliZtWK3zE24A_asvYce5GUZfdmBgYZyfuir-qQbDYhNpZ8331yqjZkwoa1g',
        ],
        title: 'Hound & Gatos Chicken & Chicken Liver Formula Grain-Free Canned Food',
        age: 1,
        date: '2026-05-04',
        description: 'Formulated for active and agile cats like Abyssinians.',
        gender: Gender.Male,
        breed: 'Abyssinian',
        //isLiked: false,
        isPet: false,
        price: 1100,
      ),
      Details(
        image: [
          'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTeW7b7kmagekEVc3PrXWd0KN4UFHQPU1T1cGctTNoc8kh77eFso9aRY9oTG2ONImHdpdBwDj_iPmLbqMXt10FQT40HMg6FqDPLErfIEG27OlyVAYKB2ysMCw',
          'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSTxGBUQpGN58TV2iPI54cZeZ8i-ZrDJJGyGhJpQtfffD-hdMR1VDC1iYYRfWVA8X9ddxlStcVmo53OEtnBID9YHBlt6MAz7xSro4F_nTnyOtXLHhL2Aeufeg',
        ],
        title: 'Purina ONE Indoor Advantage',
        age: 1,
        date: '2026-05-04',
        description: 'Maintains coat health and controls weight gain in Russian Blues.',
        gender: Gender.Female,
        breed: 'Russian Blue',
        //isLiked: false,
        isPet: false,
        price: 1150,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRV3W0nUcsInWrFQfX8fD7O5Jce8uEqR9Rr9wXbXQq9tGFve--bEhjeVBfNESJW8eLE5mUwd3E6jHgdb4jQnFYnFfWtXl6cqO86H3sBnfCoNf7hhEw9Q7hI0w',
          'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcS2aMlpgRgnAzCWaOSZJNk8ZRBkwlW03s9-PwHjM0_KYwDLtiLJli0E9i8GYmYb1OQJNGEwIjKKzh9fzBwUOfLuOuiL0pjQlHZaKFulDQb1MmxvuTDso-yZ',
        ],
        title: 'Blue Buffalo Freedom Indoor Adult Chicken Recipe Grain-Free Dry Cat Food',
        age: 1,
        date: '2026-05-04',
        description: 'Supports urinary health and coat shine in American Shorthairs.',
        gender: Gender.Male,
        breed: 'American Shorthair',
        //isLiked: false,
        isPet: false,
        price: 1000,
      ),
      Details(
        image: [
          'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcT13tW4a9PNvfLfylS3y9wWURIxaAaAK2_wa-Bh2XEJ8JXN6A-rA-Rx898uK2sICzNSJF206qBqVHq4ADqG0prUcPYzhRG3tWhb7OD0LG-l1uNk3srC9PGMyA',
          'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcT69L8wg8CHangA8k9ooW9C6CdZV6exDUr9H94y0UJtJFi9fEu9V7B-2wSD2HzzUUp2RQlmqMgI4S0Ls8TnWVVshet33g9DCfbYjy0f00mlS_LZno5dWZerpg',
        ],
        title: 'Royal Canin Indoor Adult Dry Cat Food',
        age: 1,
        date: '2026-05-04',
        description: "Enhances skin health and supports Birman cat's gentle nature.",
        gender: Gender.Female,
        breed: 'Birman',
        //isLiked: false,
        isPet: false,
        price: 1250,
      ),
      Details(
        image: [
          'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcThVJhZir_Z-AgD2wrVWNGliff1j850--u3c99FLZNhOqleKveN9nNpanXLwkaoqH2QorySbu8wkp1fduFxA9J90e1tOawdgv06k9AVLQoKs-N3pjbO6saE5w',
          'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSbi6hIXTL4Cu9S0W3EGrTNDD8H_eKeSDNZp5Z4a4Vbb5cxxUo78wldkEwPeFOldWQMjEGzGknShccRI_QUy4FV6GvGTNNYo3IeMgQsUlEy4T84j8Gg-DEMrZI',
        ],
        title: 'Purina Cat Chow Naturals Original',
        age: 1,
        date: '2026-05-04',
        description: 'Calorie-dense formula tailored for the energetic Sphynx breed.',
        gender: Gender.Male,
        breed: 'Sphynx',
        //isLiked: false,
        isPet: false,
        price: 1550,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcR4LqkMfCNzpgz9nEeITjHeNrI2clE4G5syr-Lc9eTS3QnBsaCrw2CNm470wHgyKovonnyROWQgZHkK3pLMKOZA3tjiIqDz9w3MESrwMSSldtbKperI1iJe',
          'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRc9T2iCwAaBbtFFRbt_jQbBz9soeuu0kTkP7-ZAH-wVQmSpJE26Qjsl0pX6784-mFP81q2j3k1mrounAjQ_1AvM27K2MIyQw2004ZBXkzCdgY5DX9SSWrr',
        ],
        title: 'IAMS Proactive Health Adult Healthy Dry Cat Food with Chicken',
        age: 1,
        date: '2026-05-04',
        description: 'Boosts immunity and maintains thick coat for Siberian cats.',
        gender: Gender.Female,
        breed: 'Siberian',
        //isLiked: false,
        isPet: false,
        price: 1350,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRPPaSUSZTpxB_EKzp2UjKYf0VaHg-an7a88PjrK-WA6_aqIt6C4dvZ9uvlk0SpoTj7LBA8qPbJUSPCP_ylIV8ypF8yho8r15KECyZQ5O3PGzRXAeh4pGfxFg',
          'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTDSCR6PXVSIQVn8HkvEZf6jlNcrPUT_tNBOO6nCqWL8frvCzD7xfr0vK3isEmRqXZbTWsgddGSLzbW2Qyvnit8qnXzPD9Nmm3AyNc7zSfkw_Ddal-U9W55Dg',
        ],
        title: "Hill's Science Plan Sensitive Stomach & Skin Adult Cat Dry Food",
        age: 1,
        date: '2026-05-04',
        description: 'Formulated to support spine and digestive health in Manx cats.',
        gender: Gender.Male,
        breed: 'Manx',
        //isLiked: false,
        isPet: false,
        price: 1200,
      ),
      Details(
        image: [
          'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTtgCAWCGQJrztALA2MyPyVHRwCNyr_kHLZBwCvKQqZ3KzLk-HUtrJwCDMpNZQr7Z7es-VmM-thKTuGvpxKAOfVcwfkdygganUeRzLANkNMWX8spMMbnI_XB5s',
          'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRsGWiVVYxnODTsvUEUTZFNwd_GzYpxfQOveaz9k8nn5PnuZsZX2ayms4rVgM2OXKdYwfaLf6lEMoKnNhL_Lhaj5B_l8xxgfE7ZLPXZKlerkCBAdruHNNSIdDQ',
        ],
        title: 'Royal Canin Indoor Adult Dry Cat Food',
        age: 1,
        date: '2026-05-04',
        description: 'Supports muscular build and soft coat of Chartreux cats.',
        gender: Gender.Female,
        breed: 'Chartreux',
        //isLiked: false,
        isPet: false,
        price: 1300,
      ),
      Details(
        image: [
          'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT6v8eQUYkpG5BwaXB8l7X9p7J2wZcQRPRmtK3wFgq-wSxrkg5fWm8q6UnnH_guSTC4iwCmSDKV5yn9afJLkl2qcZXyz0TN8TH5Cw1wJIZJ1mphrk14iMeDzg',
          'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT61TE5SgY8TOjOeJc--oPgGTRAkMtYScCHEFREbjnVeNE3-dZlAaQ-l4C_rQvtrV-5ufFiBtBXikDAzpMXuZJhJNe3Xv-b0t9-1-Z8dOpvjpMYqa5w6AvrPQ',
        ],
        title: 'Blue Buffalo Wilderness High Protein Grain-Free',
        age: 1,
        date: '2026-05-04',
        description: "High-protein formula to support Ocicat's active lifestyle.",
        gender: Gender.Male,
        breed: 'Ocicat',
        //isLiked: false,
        isPet: false,
        price: 1450,
      ),
      Details(
        image: [
          'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQpwxptwr6uMYp616fyHdGgG0sGtas2-82pzaZVXqLdtGHdst2ts93YUHGVKV2QuJkdJ1SHHhy7Sb-Li5n1QP7pQGF1Q-iXG2M3MJA7mUj-Zm2s4iubeBTv',
          'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSTMkFqNa71bhAYzGgHv4mP_AWUHVjmWlABI035hJLIe-nLficqfcIH6CobfKz9KNEbq1Suf2KWIpOTMuP0P5Svxfky4xXFfQ',
        ],
        title: 'IAMS Proactive Health Adult Healthy Dry Cat Food with Chicken',
        age: 1,
        date: '2026-05-04',
        description: 'Provides essential nutrients for thick coat and bone health.',
        gender: Gender.Female,
        breed: 'Norwegian Forest Cat',
        //isLiked: false,
        isPet: false,
        price: 1400,
      ),
      Details(
        image: [
          'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT2hdwOnaSPt156RT6qvXTGpiXfnyn2X3PoMXRPkrmHzJRKfw-QIDtWKsK1yzcEs_eSHAuWj0CJkIZhr0hW439V3HtBJIFWF-QUCUDwX4EU3ZeORjnYVFNH',
          'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTeW7b7kmagekEVc3PrXWd0KN4UFHQPU1T1cGctTNoc8kh77eFso9aRY9oTG2ONImHdpdBwDj_iPmLbqMXt10FQT40HMg6FqDPLErfIEG27OlyVAYKB2ysMCw',
        ],
        title: 'Purina ONE Indoor Advantage',
        age: 1,
        date: '2026-05-04',
        description: 'Supports black coat brilliance and sensitive digestion.',
        gender: Gender.Male,
        breed: 'Bombay',
        //isLiked: false,
        isPet: false,
        price: 1250,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQ9SdFvwgPKRInyzaejPpRvQ7NjyIL1P8uS5xZRaMC855Hl8iUxxsDMbgCurbS68UhfDh7y7NXgzXhN22C1hfIsd4pojaWBXWNXqtvntKrn9bKmj5QQZRy8dQ',
          'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT3ueRZlMk0-9kdMcJw8X1mp29EDhjq8RilkZPo8xM4zEJD8ATRhPKLR_0dLMMoQW6c4sxMYGZlKbD3Cf6fWaRSR2-1xcx1jJ9KDd6S456Sd9FXaX3exUmrIA',
        ],
        title: 'Purina Pro Plan Sensitive Skin and Stomach Cat Food',
        age: 1,
        date: '2026-05-04',
        description: 'A light and energetic formula for the slender Cornish Rex.',
        gender: Gender.Female,
        breed: 'Cornish Rex',
        //isLiked: false,
        isPet: false,
        price: 1150,
      ),
    ],
  ),
  Heading(
    title: 'Bird Food',
    icon: 'https://static.thenounproject.com/png/672295-200.png',
    lists: [
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnh_oVC2GXKTHO2vW6TuFwF40cqUo64r2uWQ&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQezCUrXc5R2z81U7lefDhqgcuc79kLB1KmjA&s',
        ],
        title: 'Sun Conure Food',
        age: 1,
        date: '2026-05-04',
        description: 'Formulated to support the healthy joints, coat, and overall vitality of Sun Conures.',
        gender: Gender.Male,
        breed: 'Sun Conure',
        //isLiked: false,
        isPet: false,
        price: 20,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQd-NCKhl9zsHB7Ums95IVhiVNZRyB8fwus7A&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrd7gyrMbMH4cArvPVTjeT0tFFiUzDsynPQw&s',
        ],
        title: 'Amazon Parrot Food',
        age: 1,
        date: '2026-05-04',
        description: 'Specially formulated for the health and well-being of Amazon Parrots.',
        gender: Gender.Male,
        breed: 'Amazon Parrot',
        //isLiked: false,
        isPet: false,
        price: 25,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_YGYLfGPB4hbGCLTYNm5Z9ZZBs7L3bogcEw&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTz0bE1dz8RR2QmadZUCqzRFGSUy2oRs8Fnqg&s',
        ],
        title: 'Peach-faced Lovebird Food',
        age: 1,
        date: '2026-05-04',
        description: 'Supports the health and longevity of Peach-faced Lovebirds.',
        gender: Gender.Male,
        breed: 'Peach-faced Lovebird',
        //isLiked: false,
        isPet: false,
        price: 18,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEnUvTNyO_O8fMz8WPEjxkL-2pxU3E64jzMg&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZqHVxsb-v9KRxXE9eLKLmWkGU5ZiNstO8Ig&s',
        ],
        title: 'Cockatiel Food',
        age: 1,
        date: '2026-05-04',
        description: 'Nutritionally balanced food for Cockatiels to ensure a long, healthy life.',
        gender: Gender.Male,
        breed: 'Cockatiel',
        //isLiked: false,
        isPet: false,
        price: 22,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSecBsuvQbeSqe9n3f7KuME3MTYmxOQQSFaiA&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaxtYZKOWkSR8kHriSFNHxdksO-_zUN_uN-Q&s',
        ],
        title: 'Budgerigar (Budgie) Food',
        age: 1,
        date: '2026-05-04',
        description: 'Premium food for Budgerigars, promoting optimal health and well-being.',
        gender: Gender.Male,
        breed: 'Budgerigar',
        //isLiked: false,
        isPet: false,
        price: 15,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRd6vBw_XU96bJSQCITzt9jPoGxkE-M3cMbg&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPZvQW--_eM5cOSqI1abOkOfMyML3DUMpgNA&s',
        ],
        title: 'African Grey Parrot Food',
        age: 1,
        date: '2026-05-04',
        description: 'A specially designed formula to support the unique needs of African Grey Parrots.',
        gender: Gender.Male,
        breed: 'African Grey Parrot',
        //isLiked: false,
        isPet: false,
        price: 30,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVj_GD3Tz4w2JKX6EiwRdhk_J6WOGO2G-6Mg&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAPlrIvBjdWdCyTrwqTbsRa3dDqrVriDV9Kg&s',
        ],
        title: 'Blue-and-Gold Macaw Food',
        age: 1,
        date: '2026-05-04',
        description: 'Nutritious food to ensure the health and vibrancy of Blue-and-Gold Macaws.',
        gender: Gender.Male,
        breed: 'Blue-and-Gold Macaw',
        //isLiked: false,
        isPet: false,
        price: 40,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTu9vUBba_04_SbUmh4PRH2fUnvP5kLfuMepQ&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFkEIAhffQD5lfIc3KYr_Swc9k4EfV0uytHQ&s',
        ],
        title: 'White-bellied Caique Food',
        age: 1,
        date: '2026-05-04',
        description: 'Designed to maintain the health and energy of White-bellied Caiques.',
        gender: Gender.Male,
        breed: 'White-bellied Caique',
        //isLiked: false,
        isPet: false,
        price: 28,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkam7Nm7HtWq6ZNK5XgBS5V761eqGJv3U3rg&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUP9EAK7jqW_L4jP2C1pm6FhD_sFOj8R1Qjw&s',
        ],
        title: 'Indian Ringneck Parakeet Food',
        age: 1,
        date: '2026-05-04',
        description: 'Healthy and balanced food for Indian Ringneck Parakeets.',
        gender: Gender.Male,
        breed: 'Indian Ringneck Parakeet',
        //isLiked: false,
        isPet: false,
        price: 20,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQie9jxwkpRRigWsFDiMIWmWiXOnlm6a1_X9A&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfSPuljW5B-dRx0KRjdP7wBaqTeFGxn-xVqA&s',
        ],
        title: "Fischer's Lovebird Food",
        age: 1,
        date: '2026-05-04',
        description: "Specially formulated food for Fischer's Lovebirds to ensure health and vitality.",
        gender: Gender.Male,
        breed: "Fischer's Lovebird",
        //isLiked: false,
        isPet: false,
        price: 18,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSG4DtQyb5Uu9bBHlH-Jd-u1I7pteXEZjUnA&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTP5axRCNhV8KifMLCkLkT067vaUadoE3d2nw&s',
        ],
        title: 'Canary Food',
        age: 1,
        date: '2026-05-04',
        description: 'High-quality food to promote the health and well-being of Canaries.',
        gender: Gender.Male,
        breed: 'Canary',
        //isLiked: false,
        isPet: false,
        price: 15,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdC_LGEAh_4P-9tzoo_HBAOwDPexmaqsa3Kw&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRwG0tZPNo0Eg_M9UWPXEPMLaKG5Y8DG6Usw&s',
        ],
        title: 'Zebra Finch Food',
        age: 1,
        date: '2026-05-04',
        description: 'Supports optimal growth and health for Zebra Finches.',
        gender: Gender.Male,
        breed: 'Zebra Finch',
        //isLiked: false,
        isPet: false,
        price: 12,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1Ce3sVlxjiVGq0jTlPuYGJJlKtOboQlmbmg&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpMzT_MfMKs-ZC5FbipETw-KhMudE-27bZFA&s',
        ],
        title: 'Pacific Parrotlet Food',
        age: 1,
        date: '2026-05-04',
        description: 'Nutritionally balanced food for Pacific Parrotlets.',
        gender: Gender.Male,
        breed: 'Pacific Parrotlet',
        //isLiked: false,
        isPet: false,
        price: 22,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNYgfvR1t1yOoUaQGFXrKKi8J0VJh-8UCnjw&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwjz0vPdVGVthMCnU9IDdZtbwp5SYz9CfFQw&s',
        ],
        title: 'Umbrella Cockatoo Food',
        age: 1,
        date: '2026-05-04',
        description: 'Food to maintain the health and vitality of Umbrella Cockatoos.',
        gender: Gender.Male,
        breed: 'Umbrella Cockatoo',
        //isLiked: false,
        isPet: false,
        price: 35,
      ),
    ],
  ),
  Heading(
    title: 'Fish Food',
    icon: 'https://creazilla-store.fra1.digitaloceanspaces.com/icons/3204509/fish-icon-md.png',
    lists: [
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCHh8o2XYcs8id0efj9Ub2wON0ZcwnAmF_zg&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROxoWhZMV8QxofJxPUh1hbH3cgel9dvtnw3Q&s',
        ],
        title: 'Betta Pro Care',
        age: 1,
        date: '2026-05-04',
        description: 'Formulated to promote the health and vitality of Betta fish.',
        gender: Gender.Male,
        breed: 'Betta',
        //isLiked: false,
        isPet: false,
        price: 20,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxP0XXqig1hvQmxaGsK0p99_LvXfeBjdSL_A&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAEHyOFE1Sm2o72kH98g_G8WIi7afIuFKnTQ&s',
        ],
        title: 'Goldfish Premium Blend',
        age: 1,
        date: '2026-05-04',
        description: 'Specially designed food for Goldfish, enhancing their color and health.',
        gender: Gender.Male,
        breed: 'Goldfish',
        //isLiked: false,
        isPet: false,
        price: 18,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzpi0SILnwO6DQ4f-6-lGXEzOo4S5Qpi9OSg&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbQZaNkAVKV3HzEcrsaVPyuGdJRUj2Ax9lIg&s',
        ],
        title: 'Guppy Gold Flakes',
        age: 1,
        date: '2026-05-04',
        description: 'High-quality food to support the growth and vitality of Guppies.',
        gender: Gender.Male,
        breed: 'Guppy',
        //isLiked: false,
        isPet: false,
        price: 15,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8qhgFKLEaPzAAdfCsdb1GOzZZX-hahbinrA&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi33HGubD2FbX2_lpL5uC_YTxSQjmrYEmyXg&s',
        ],
        title: 'Angelfish Delights',
        age: 1,
        date: '2026-05-04',
        description: 'Food designed for Angelfish to enhance their beauty and health.',
        gender: Gender.Male,
        breed: 'Angelfish',
        //isLiked: false,
        isPet: false,
        price: 22,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRionsNlHpva5hrIcRW7Xf1tdxP0YOouaB2ww&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnpULfaaxqyCctJBovdsGE74BDpzCaPhrfhQ&s',
        ],
        title: 'Molly Balanced Diet',
        age: 1,
        date: '2026-05-04',
        description: 'Nutritionally balanced food for Mollys to support their health and longevity.',
        gender: Gender.Male,
        breed: 'Molly',
        //isLiked: false,
        isPet: false,
        price: 20,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIFXrZWKzg4PSDNLq7GP01bK5fy-b4GySVuQ&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA7SRJTn6_ygY_s5ZJ9KLIMy9bAN8FYz17iQ&s',
        ],
        title: 'Neon Tetra Glow',
        age: 1,
        date: '2026-05-04',
        description: 'Special food for Neon Tetras to support their vibrant colors and health.',
        gender: Gender.Male,
        breed: 'Neon Tetra',
        //isLiked: false,
        isPet: false,
        price: 12,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ85H5Q2VDsD90tctj6ZmJbNWaFBZUq8vsumQ&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRA0pTiHmeNDLoJF__1CFVjotlwz9aFze988Q&s',
        ],
        title: 'Oscar Power Pellet',
        age: 1,
        date: '2026-05-04',
        description: 'Food designed for the large and powerful Oscar fish.',
        gender: Gender.Male,
        breed: 'Oscar',
        //isLiked: false,
        isPet: false,
        price: 25,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQnNoqEUwO12iI_AgJG4RZ4I9xDjZDiIx4Vw&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSt5WgIlw8NUNWCdRMAuh0AZvDxFV7oUDsf-w&s',
        ],
        title: 'Platy Vital Mix',
        age: 1,
        date: '2026-05-04',
        description: 'Premium food for Platys to ensure healthy growth and vitality.',
        gender: Gender.Male,
        breed: 'Platy',
        //isLiked: false,
        isPet: false,
        price: 16,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6gXu9n8ja4fednyKZe-NUnxhPTSfb-v8fpQ&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmHG_2zL_xi6jdxe-sXP-K2Bdh10UTqEcsrw&s',
        ],
        title: 'Discus Supreme',
        age: 1,
        date: '2026-05-04',
        description: 'High-quality food to support the health and color vibrancy of Discus fish.',
        gender: Gender.Male,
        breed: 'Discus',
        //isLiked: false,
        isPet: false,
        price: 30,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHBo4fsn9mqzpfR_7XfU8VUjgVqajAH1FLmA&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlNe9zTGzHMxakg9nS4X7u7MEcVYAt1w2FZw&s',
        ],
        title: 'Pearl Gourami Formula',
        age: 1,
        date: '2026-05-04',
        description: 'Specially formulated food for Pearl Gouramis to maintain their health.',
        gender: Gender.Male,
        breed: 'Pearl Gourami',
        //isLiked: false,
        isPet: false,
        price: 22,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-WD2vP29DFnat2O0wgC_uP_ES6bEOSw5Gtw&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTGdHkosqjgAr-f0LQvDe_yJ4PoaPDGn_mnw&s',
        ],
        title: 'Kuhli Loach Treats',
        age: 1,
        date: '2026-05-04',
        description: 'Designed to meet the dietary needs of Kuhli Loaches.',
        gender: Gender.Male,
        breed: 'Kuhli Loach',
        //isLiked: false,
        isPet: false,
        price: 18,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTG9oeepubW2t-wCtgP7Jr2cOoF3VUHtQPqxg&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZq_AZOO8iGD6d7G3Ke9RIadwCGFq45cyQwA&s',
        ],
        title: 'Corydoras Catfish Crunch',
        age: 1,
        date: '2026-05-04',
        description: 'Nutritionally balanced food for Corydoras Catfish to enhance their health.',
        gender: Gender.Male,
        breed: 'Corydoras Catfish',
        //isLiked: false,
        isPet: false,
        price: 20,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_vQubwyIXK0c8Ksn_ipHIfUqaG5dc4eAkDg&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYnkKZJA7fPiFbax24QfVP8W9OIr0Cq5ZqRg&s',
        ],
        title: 'Plecostomus Algae Pellets',
        age: 1,
        date: '2026-05-04',
        description: 'Specially designed food for Plecostomus to support their growth and health.',
        gender: Gender.Male,
        breed: 'Plecostomus',
        //isLiked: false,
        isPet: false,
        price: 28,
      ),
      Details(
        image: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZWtLrsSGCqvI2N5ecl_5gYLyelHqe3ALhVw&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTb21BTF4VaVijyWnIaCwAiyxM3XY2pB8dhZA&s',
        ],
        title: 'Rainbowfish Color Boost',
        age: 1,
        date: '2026-05-04',
        description: 'Healthy food to support the vibrant colors and health of Rainbowfish.',
        gender: Gender.Male,
        breed: 'Rainbowfish',
        //isLiked: false,
        isPet: false,
        price: 25,
      ),
    ],
  ),
];
